/*

-- =============================================
-- Author:		Evgeni Yordanov, Alexandrina Ivanova, Mihail Kostov
-- Create date: 2013-03-11
-- Description:	Pie chart JavaScript library. It uses SVG/VML/Canvas rendering to display the chart.
-- Version: 1.0
-- =============================================


	USE LICENSE
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on Research Metrics, LLC's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
			- modify or copy the materials;
			- use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
			- attempt to decompile or reverse-engineer any software contained on Research Metrics, LLC's web site;
			- remove any copyright or other proprietary notations from the materials; or
			- transfer the materials to another person or "mirror" the materials on any other server.
		This license shall automatically be terminated if you violate any of these restrictions, and may be terminated by Research Metrics, LLC at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	
	DISCLAIMER
		The materials on Research Metrics, LLC's web site are provided "as is". Research Metrics, LLC makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Research Metrics, LLC does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	
	LIMITATIONS
	In no event shall Research Metrics, LLC or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Research Metrics, LLC's Internet site, even if Research Metrics, LLC or a Research Metrics, LLC authorized representative has been notified orally or in writing of the possibility of a such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
	
	GOVERNING LAW
	Any claim relating to Research Metrics, LLC's web site shall be governed by the laws of the State of Perrysburgs without regard to its conflict of law provisions.

*/

function PieChart(p,n,g){if("undefined"!==typeof p&&"object"===typeof n){"undefined"===typeof window.Pie&&(window.Pie={});if("undefined"===typeof g){for(var q=0;"undefined"!==typeof Pie[q];)q++;g=q}window.Pie[g]={width:0,height:0,params:n,container:p,chartContainer:null,initialize:function(a,b,c){var d=Pie[g];if("undefined"===typeof n.xmlData&&"undefined"===typeof n.container){var f={xmlData:{chart:n},container:d.container};n=f;d.params=f}n.xmlData.chart=d.dataProxy.changeDataFormat(n.xmlData.chart);
"undefined"!==typeof c&&(n=c,d.params=n);if(d.ParamsChecker.checkParams(n))a=d.ParamsChecker.getSizeFromParams(a,b,d.container),d.width=a.width,d.height=a.height,d.Render.InitializeRender(),a=d.NodeFactory[d.Render.render],d.deleteChilds(d.container),d.chartContainer=d.createChartContainer(d.container),d.ToolTip.initialize(),d.Base.drawTitle(),d.Base.initBaseParams(),a.createRoot(),a.createBackground(),d.Base.drawCircleParts({opacity:1,tooltip:!1,overlays:!0}),parseInt(n.xmlData.chart.legend)&&d.Base.drawLegend(),
d.Base.drawCircleParts({opacity:0,tooltip:!0,overlays:!1}),d.Base.appendDocumentRef(),d.Base.drawLogo();else throw Error("Incorrect parameters passed to Pie Chart initialization!");},dataProxy:{changeDataFormat:function(a){var b={};if("undefined"!==typeof a.base){for(var c in a)if("set"!==c&&"categories"!==c&&"styles"!==c)for(var d in a[c])"rotateCategoryNames"===d?b.rotateNames=a[c][d]:"showLegend"===d?b.legend=a[c][d]:"showAxisHeadingsOnHover"===d?b.headingsHover=a[c][d]:b[d]=a[c][d];else if("set"===
c)b.set=a[c];else if("categories"===c||"styles"===c)b[c]=a[c];return b}if("object"===typeof a.set)return a}},degToRad:function(a){return a*(Math.PI/180)},Base:{titleTopMargin:15,titleHeight:30,circlePadding:0.1,valueSum:0,chartBorder:0.3,legendPadding:0,legendPaddingBottom:20,colorDefaultVault:{colorArrayLight:"fadb7b D3EAFB BFD973 FFC199 73C1C1 E89999 C199C1 A3BC88 D5D073 73C1E8 cbbcdb c9777a".split(" "),validationObj:{1:!0,2:!0,3:!0,4:!0,5:!0,6:!0,7:!0,8:!0,9:!0,"0":!0,a:!0,b:!0,c:!0,d:!0,e:!0,
f:!0,A:!0,B:!0,C:!0,D:!0,E:!0,F:!0},counter:0,getColor:function(){var a=Pie[g].Base.colorDefaultVault,b=a.colorArrayLight,c=a.counter;c>=b.length&&(c%=b.length);b=b[c];a.counter++;return b},testColor:function(a){var b=!1,c=Pie[g].Base.colorDefaultVault.validationObj;if("undefined"!==typeof a){a=a.replace("#","");if(6<a.length)return b;for(var d=0;d<a.length;d++)if("undefined"!==typeof c[a.charAt(d)])b=c[a.charAt(d)];else{b=!1;break}}return b}},getBiggestBBox:function(a,b){var c=Pie[g],d=a.length,
f=document.createElement("div"),e=0,h=0;f.style.top="-100px";f.style.left="-100px";f.style.position="absolute";f.style.fontFamily=b.fontFamily;f.style.fontSize=b.fontSize+"px";for(c.chartContainer.appendChild(f);d--;){c.deleteChilds(f);f.appendChild(document.createTextNode(a[d]));var k=c.getSize(f);e<k.width&&(e=k.width);h<k.height&&(h=k.height)}c.chartContainer.removeChild(f);return{w:e,h:h}},circleParams:{x:0,y:0,r:0},piePosition:{x:0,y:0,w:0,h:0},legendPosition:{x:0,y:0,w:250,h:0},symbols:[{symbol:/&#34;/g,
replacement:'"'},{symbol:/&quot;/g,replacement:'"'},{symbol:/&ldquo;/g,replacement:"\u201c"},{symbol:/&#8220;/g,replacement:"\u201c"},{symbol:/&rdquo;/g,replacement:"\u201d"},{symbol:/&#8221;/g,replacement:"\u201d"},{symbol:/&#39;/g,replacement:"'"},{symbol:/&#8216;/g,replacement:"\u2018"},{symbol:/&#8217;/g,replacement:"\u2019"}],encodeString:function(a){for(var b=Pie[g].Base.symbols,c=b.length;c--;)a=a.replace(b[c].symbol,b[c].replacement);return a},drawLogo:function(){var a=Pie[g];a.NodeFactory[a.Render.render].drawLogo.init()},
appendDocumentRef:function(){var a=Pie[g];null!==a.NodeStore.documentFragmentRef&&a.chartContainer.appendChild(a.NodeStore.documentFragmentRef)},initBaseParams:function(){var a=Pie[g],b=a.params.xmlData.chart,c=0,d=0,f=0;a.Base.legendPadding=parseInt(b.legendPadding,10);a.Base.legendPosition.w=parseInt(b.legendWidth,10);a.Base.getMaxValue();""!==b.caption&&(d=a.Base.titleHeight+a.Base.titleTopMargin);var e=a.height-d,d=0+d;"1"===b.legend?(c=a.Base.legendPosition.w,a.Base.legendPosition.h=e,a.Base.legendPosition.y=
d):a.Base.legendPadding=0;var h=a.width-c-a.Base.legendPadding;"right"===b.legendPosition?(f=0,a.Base.legendPosition.x=h):(f=c+a.Base.legendPadding,a.Base.legendPosition.x=0);a.Base.piePosition.x=0+f;a.Base.piePosition.y=d;a.Base.piePosition.w=h;a.Base.piePosition.h=e;a.Base.circleParams.x=a.Base.piePosition.x+a.Base.piePosition.w/2;a.Base.circleParams.y=a.Base.piePosition.y+a.Base.piePosition.h/2;a.Base.circleParams.r=a.Base.piePosition.w>a.Base.piePosition.h?a.Base.piePosition.h/2-a.height*a.Base.circlePadding:
a.Base.piePosition.w/2-a.width*a.Base.circlePadding},defineUndefinedFontStyles:function(a){"undefined"===typeof a.bold&&(a.bold="0");"undefined"===typeof a.font&&(a.font="Tahoma");"undefined"===typeof a.size&&(a.size="10");"undefined"===typeof a.color&&(a.color="000000");return a},polyHoverHandler:function(a,b){return function(){"SVG"===Pie[g].Render.render&&this.setOpacity(0.4);Pie[g].ToolTip.show(a);if("VML"===Pie[g].Render.render&&"undefined"!==typeof b.pie&&"undefined"!==typeof b.color){b.pie.removeChild(b.pie.lastChild);
var c=Pie[g].NodeFactory.VML.createNode("fill");c.setAttribute("Color","#"+b.color.replace("#",""));c.setAttribute("opacity",b.opacity+0.4);b.pie.appendChild(c)}}},polyOutHandler:function(a){return function(){"SVG"===Pie[g].Render.render&&this.setOpacity(0);Pie[g].ToolTip.hide();if("VML"===Pie[g].Render.render&&"undefined"!==typeof a.pie&&"undefined"!==typeof a.color){a.pie.removeChild(a.pie.lastChild);var b=Pie[g].NodeFactory.VML.createNode("fill");b.setAttribute("Color","#"+a.color.replace("#",
""));b.setAttribute("opacity",a.opacity-0.5);a.pie.appendChild(b)}}},getMaxValue:function(){for(var a=Pie[g],b=a.params.xmlData.chart.set,c=0,d=0,f=b.length;d<f;d++)c+=parseFloat(b[d].value,10);a.Base.valueSum=c},getDegreeFromValue:function(a){return 360*(a/Pie[g].Base.valueSum)},drawCircleParts:function(a){var b=Pie[g],c=b.params.xmlData.chart,d=c.set,f=d.length,e=270,h="",h="0"===c.innerRadius?"drawCirclePart":"drawCirclePartWithInnerRadius";if("1"===c.chartShadow)b.Base[h]({angleStart:0,angleEnd:360,
color:"9a9a9a",shadow:!0,stroke:!1,opacity:a.opacity,tooltip:!1});if(1===c.set.length&&0==c.set[0].value)b.Base[h]({angleStart:0,angleEnd:360,color:"ffffff",shadow:!1,stroke:!1,opacity:0.5,tooltip:!1});else for(var k=0;k<f;k++){var j=b.Base.getDegreeFromValue(parseFloat(d[k].value,10)),l=d[k].color,m="",m=m+d[k].label,m=m+" "+c.numberPrefix+parseFloat(d[k].value,10).toFixed(c.decimals)+c.numberSuffix;b.Base[h]({angleStart:e,angleEnd:j+e,color:l,stroke:!0,opacity:a.opacity,tooltip:m,url:d[k].url});
e+=j}a.overlays&&b.Base.drawOverlays()},drawCirclePartWithInnerRadius:function(a){var b=Pie[g],c=[],d=b.Base.circleParams.x,f=b.Base.circleParams.y,e=b.Base.circleParams.r,h=b.NodeFactory[b.Render.render],k=parseFloat(b.params.xmlData.chart.innerRadius,10);"undefined"===typeof a.shadow&&(a.shadow=!1);"undefined"===typeof a.stroke&&(a.stroke=!1);for(var j=a.angleStart;j<=a.angleEnd;j++){var l=b.degToRad(j),m=0,n=0,m=d+e*Math.cos(l),n=f+e*Math.sin(l);c.push({x:m,y:n})}for(j=a.angleEnd;j>=a.angleStart;j--)l=
b.degToRad(j),n=e*k,m=d+n*Math.cos(l),n=f+n*Math.sin(l),c.push({x:m,y:n});h.drawPoly({points:c,color:a.color,shadow:a.shadow,stroke:a.stroke,opacity:a.opacity,tooltip:a.tooltip,url:a.url})},drawCirclePart:function(a){var b=Pie[g],c=[],d=b.Base.circleParams.x,f=b.Base.circleParams.y,e=b.Base.circleParams.r,h=b.NodeFactory[b.Render.render];"undefined"===typeof a.shadow&&(a.shadow=!1);"undefined"===typeof a.stroke&&(a.stroke=!1);c.push({x:d,y:f});for(var k=a.angleStart;k<=a.angleEnd;k++){var j=b.degToRad(k),
l=0,m=0,l=d+e*Math.cos(j),m=f+e*Math.sin(j);c.push({x:l,y:m})}h.drawPoly({points:c,color:a.color,shadow:a.shadow,stroke:a.stroke,opacity:a.opacity,tooltip:a.tooltip,url:a.url})},drawOverlays:function(){var a=Pie[g],b=a.params.xmlData.chart,c=a.NodeFactory[a.Render.render],d=0,f=0,e=a.Base.circleParams.r;"0"!==b.innerRadius&&(d=parseFloat(b.innerRadius,10)*e);f=parseFloat(b.overlay,10)*e;c.drawOverlay({innerRadius:d+a.Base.chartBorder,outerRadius:f,x:a.Base.circleParams.x,y:a.Base.circleParams.y,type:"inner"});
c.drawOverlay({innerRadius:f,outerRadius:e-a.Base.chartBorder,x:a.Base.circleParams.x,y:a.Base.circleParams.y,type:"outer"})},drawLegend:function(){var a=Pie[g],b=a.params.xmlData.chart,c=a.NodeFactory[a.Render.render],d=document.createElement("div"),f=a.Base.legendPosition.w,e="right"!==b.legendPosition?a.Base.legendPadding:a.width-(f+a.Base.legendPadding),h=a.Base.legendPosition.y,k=a.Base.legendPosition.h-a.Base.legendPaddingBottom;d.style.position="absolute";d.style.width=f+"px";d.style.maxHeight=
k-10+"px";d.style.left=e+"px";d.style.top=h+"px";d.style.overflowY=b.printPreview?"hidden":"auto";d.style.overflowX="hidden";d.style.zIndex="100";d.style.marginTop="6px";a.chartContainer.appendChild(d);a.NodeStore.legendContainer=d;a=a.Base.fillLegend({x:e,y:h,w:f,h:k,color:b.legendBackground,angle:b.legendBgAngle});c.drawLegendBackground(a)},fillLegend:function(a){for(var b=Pie[g],c=b.params.xmlData.chart,d=b.NodeStore.legendContainer,f=c.set,e=b.Base.legendPosition.w,h=0,k=f.length;h<k;h++){var j=
document.createElement("div");j.style.width=e-20+"px";j.style.height="auto";j.style.lineHeight=c.printPreview?"12px":"20px";j.style.padding="0";j.style.fontFamily=c.baseFont;j.style.fontSize=c.baseFontSize+"px";j.style.color="#"+c.baseFontColor;j.style.position="relative";j.style.left="10px";j.style.overflow="hidden";j.style.borderBottom="1px solid #888888";var l=document.createElement("div");l.style.cssFloat="left";l.style.styleFloat="left";l.style.margin="0px";l.style.overflow="hidden";l.style.width=
"20px";l.style.height="20px";var m=document.createElement("div");m.style.width="12px";m.style.height="12px";m.style.top="4px";m.style.left="2px";m.style.position="relative";m.style.background="#"+f[h].color.replace("#","");l.appendChild(m);j.appendChild(l);var n=c.numberPrefix+parseFloat(f[h].value,10).toFixed(c.decimals)+c.numberSuffix,m=document.createElement("div");m.style.cssFloat="left";m.style.styleFloat="left";m.style.margin=c.printPreview?"5px 0 0 0px":"0 0 0 0px";m.style.overflow="hidden";
m.style.height="auto";if(c.printPreview){var p=(f[h].label+" ("+n+")").length,q=b.Base.getBiggestBBox([f[h].label+" ("+n+")"],{fontFamily:c.baseFont,fontSize:c.baseFontSize});if(q.w>e-50){for(;q.w>e-50;)p-=10,q=b.Base.getBiggestBBox([f[h].label.slice(0,p)+"... ("+n+")"],{fontFamily:c.baseFont,fontSize:c.baseFontSize});m.appendChild(document.createTextNode(f[h].label.slice(0,p)+"... ("+n+")"))}else m.appendChild(document.createTextNode(f[h].label+" ("+n+")"))}else m.appendChild(document.createTextNode(f[h].label+
" ("+n+")"));j.appendChild(m);d.appendChild(j);j=b.getSize(j).width-b.getSize(l).width;m.style.maxWidth=j-10+"px"}c=b.NodeStore.legendContainer.clientHeight;d=parseInt(b.NodeStore.legendContainer.style.maxHeight,10);c>d&&(b.NodeStore.legendContainer.style.height=d+"px");d=b.height/2-c/2;b.NodeStore.legendContainer.style.top=d+"px";a.h=c+2*parseInt(b.NodeStore.legendContainer.style.marginTop,10);a.y=d;return a},drawTitle:function(){var a=Pie[g],b=a.params.xmlData.chart;if(""!==b.caption){var c=a.ParamsChecker.getTitleStyles(),
d=document.createElement("div"),c=a.Base.defineUndefinedFontStyles(c);d.style.top=a.Base.titleTopMargin+"px";d.style.left="0px";d.style.position="absolute";d.style.width="100%";var f=document.createElement("div");f.style.margin="auto";f.style.overflow="hidden";f.style.position="relative";f.style.width="85%";f.style.textAlign="center";f.style.fontFamily=c.font;f.style.fontSize=c.size+"px";f.style.color="#"+c.color;"1"===c.bold&&(f.style.fontWeight="bold");f.appendChild(document.createTextNode(b.caption));
d.appendChild(f);a.container.appendChild(d);a.Base.titleHeight=a.getSize(d).height}}},ParamsChecker:{stylesDefined:!1,getSizeFromParams:function(a,b,c){var d=!1,f=!1,e=0,h=0;c=Pie[g].getSize(c);var k=typeof a,j=typeof b;"undefined"!==k&&(d=!0,e="string"===k?null!==a.match("%")?parseInt(c.width*parseFloat(a,10)/100,10):isNaN(parseInt(a,10))?c.width:parseInt(a,10):"number"===k?parseInt(a,10):c.width);"undefined"!==j&&(f=!0,h="string"===j?null!==b.match("%")?parseInt(c.height*parseFloat(b,10)/100,10):
isNaN(parseInt(b,10))?c.height:parseInt(b,10):"number"===j?parseInt(b,10):c.height);d||(e=c.width);f||(h=c.height);return{width:e,height:h}},checkParams:function(){var a=Pie[g],b=!0;a.ParamsChecker.defineLegend();a.ParamsChecker.defineCaption();a.ParamsChecker.defineInnerRadius();a.ParamsChecker.defineOverlay();a.ParamsChecker.checkStyles();a.ParamsChecker.defineFonts();a.ParamsChecker.defineDecimals();a.ParamsChecker.defineSuffixPreffix();a.ParamsChecker.defineBackground();a.ParamsChecker.defineTooltip();
a.ParamsChecker.defineBorderProperties();a.ParamsChecker.encodeLabels();a.ParamsChecker.defineChartShadow();a.ParamsChecker.printPreview();a.ParamsChecker.checkSets()||(b=!1);return b},defineChartShadow:function(){var a=Pie[g].params.xmlData.chart;"undefined"===typeof a.chartShadow&&(a.chartShadow="1")},encodeLabels:function(){var a=Pie[g],b=a.params.xmlData.chart;"undefined"===typeof b.set.length&&(b.set=[b.set]);for(var c=b.set.length;c--;)b.set[c].label="undefined"!==typeof b.set[c].label?a.Base.encodeString(b.set[c].label):
""},defineBorderProperties:function(){var a=Pie[g],b=a.params.xmlData.chart;if("undefined"===typeof b.borderColor||!a.Base.colorDefaultVault.testColor(b.borderColor))b.borderColor="default";"undefined"===typeof b.borderWidth&&(b.borderWidth="1")},defineTooltip:function(){var a=Pie[g],b=a.params.xmlData.chart;if("undefined"===typeof b.toolTipBgColor||!a.Base.colorDefaultVault.testColor(b.toolTipBgColor))b.toolTipBgColor="eaeaea";if("undefined"===typeof b.toolTipBorderColor||!a.Base.colorDefaultVault.testColor(b.toolTipBorderColor))b.toolTipBorderColor=
"e7e7e7";"undefined"===typeof b.toolTipBorderWidth&&(b.toolTipBorderWidth="1");"undefined"===typeof b.toolTipFontFamily&&(b.toolTipFontFamily="Tahoma, Arial");"undefined"===typeof b.toolTipFontSize&&(b.toolTipFontSize="10");if("undefined"===typeof b.toolTipFontColor||!a.Base.colorDefaultVault.testColor(b.toolTipFontColor))b.toolTipFontColor="333333"},checkStyles:function(){var a=Pie[g],b=a.params.xmlData.chart,c=!1,d=!1,f=!1;"undefined"!==typeof b.styles&&("undefined"!==typeof b.styles.application&&
"undefined"!==typeof b.styles.application.apply&&("undefined"===typeof b.styles.application.apply.length&&(b.styles.application.apply=[b.styles.application.apply]),d=!0),"undefined"!==typeof b.styles.definition&&"undefined"!==typeof b.styles.definition.style&&("undefined"===typeof b.styles.definition.style.length&&(b.styles.definition.style=[b.styles.definition.style]),f=!0));f&&d&&(c=!0);a.ParamsChecker.stylesDefined=c},getTitleStyles:function(){var a=Pie[g],b=a.params.xmlData.chart,c={};if(a.ParamsChecker.stylesDefined){for(var d=
b.styles.application.apply,f="",e=0,h=d.length;e<h;e++)"Caption"===d[e].toObject&&(f=d[e].styles);if(""!==f){b=b.styles.definition.style;e=0;for(h=b.length;e<h;e++)b[e].name==f&&"font"==b[e].type&&(c.bold="undefined"!==typeof b[e].bold?b[e].bold:"0",c.font="undefined"!==typeof b[e].font?b[e].font:"Tahoma",c.color="undefined"!==typeof b[e].color&&a.Base.colorDefaultVault.testColor(b[e].color)?b[e].color:"000000",c.size="undefined"!==typeof b[e].size?b[e].size:"10")}}return c},defineOverlay:function(){var a=
Pie[g].params.xmlData.chart;if("undefined"===typeof a.overlay)a.overlay="0.88";else if(isNaN(a.overlay))a.overlay="0.88";else{var b=parseFloat(a.overlay,10);if(1<b||0>b)a.overlay="0.88"}},checkSets:function(){var a=Pie[g],b=a.params.xmlData.chart,c=!0;if("undefined"!==typeof b.set){"undefined"===typeof b.set.length&&(b.set=[b.set]);for(var b=b.set,d=0,f=b.length;d<f;d++){if(isNaN(b[d].value)){c=!1;break}if("undefined"===typeof b[d].color||!a.Base.colorDefaultVault.testColor(b[d].color))b[d].color=
a.Base.colorDefaultVault.getColor();"undefined"===typeof b[d].url&&(b[d].url="");"undefined"===typeof b[d].label&&(b[d].label="")}}else c=!1;if(!c)throw Error("NaN passed as set value in Pice chart!");return c},defineInnerRadius:function(){var a=Pie[g].params.xmlData.chart;if("undefined"===typeof a.innerRadius)a.innerRadius="0";else{if(isNaN(a.innerRadius))throw Error("Incorrect innerRadius passed to Pie chart!");a=parseFloat(a.innerRadius,10);if(1<a||0>a)throw Error("Incorrect innerRadius passed to Pie chart!");
}},defineLegend:function(){var a=Pie[g],b=a.params.xmlData.chart;"undefined"===typeof b.legend&&(b.legend="0");"undefined"===typeof b.legendPosition&&(b.legendPosition="right");"undefined"===typeof b.legendWidth?b.legendWidth="200":(b.legendWidth=parseInt(b.legendWidth),150>b.legendWidth&&(b.legendWidth=150));"undefined"===typeof b.legendPadding&&(b.legendPadding="30");if("undefined"===typeof b.legendBackground)b.legendBackground="eaeaea";else if(colors=b.legendBackground.split(" ").join("").split(","),
1==colors.length&&a.Base.colorDefaultVault.testColor(colors[0]))b.legendBackground=b.legendBackground.split(" ").join("");else if(1<colors.length){for(var c=!0,d=0,f=colors.length;d<f&&!(c=a.Base.colorDefaultVault.testColor(colors[d]),!c);d++);b.legendBackground=c?colors.join(","):"bbbbbb,FFFFFF"}"undefined"===typeof b.legendBgAngle?b.legendBgAngle=0:(b.legendBgAngle=parseInt(b.legendBgAngle),360===b.legendBgAngle&&(b.legendBgAngle=0));if("undefined"===typeof b.legendBorderColor||!a.Base.colorDefaultVault.testColor(b.legendBorderColor))b.legendBorderColor=
"999999";"undefined"===typeof b.legendBorderWidth&&(b.legendBorderWidth="1")},defineFonts:function(){var a=Pie[g],b=a.params.xmlData.chart;"undefined"===typeof b.baseFont&&(b.baseFont="Tahoma");if("undefined"===typeof b.baseFontColor||!a.Base.colorDefaultVault.testColor(b.baseFontColor))b.baseFontColor="000000";"undefined"===typeof b.baseFontSize&&(b.baseFontSize="10")},defineCaption:function(){var a=Pie[g],b=a.params.xmlData.chart;b.caption="undefined"===typeof b.caption?"":a.Base.encodeString(b.caption)},
defineDecimals:function(){var a=Pie[g].params.xmlData.chart;a.decimals="undefined"===typeof a.decimals?0:parseInt(a.decimals,10)},defineSuffixPreffix:function(){var a=Pie[g].params.xmlData.chart;"undefined"===typeof a.numberSuffix&&(a.numberSuffix="");"undefined"===typeof a.numberPrefix&&(a.numberPrefix="")},defineBackground:function(){var a=Pie[g],b=a.params.xmlData.chart;if("undefined"===typeof b.bgColor)b.bgColor="bbbbbb,FFFFFF";else if(colors=b.bgColor.split(" ").join("").split(","),1===colors.length&&
a.Base.colorDefaultVault.testColor(colors[0]))b.bgColor=b.bgColor.split(" ").join("");else if(1<colors.length){for(var c=!0,d=0,f=colors.length;d<f&&!(c=a.Base.colorDefaultVault.testColor(colors[d]),!c);d++);b.bgColor=c?colors.join(","):"bbbbbb,FFFFFF"}"undefined"===typeof b.bgAngle?b.bgAngle=0:(b.bgAngle=parseInt(b.bgAngle),360===b.bgAngle&&(b.bgAngle=0));b.bgAlpha="undefined"===typeof b.bgAlpha?100:parseInt(b.bgAlpha,10)},printPreview:function(){var a=Pie[g].params.xmlData.chart;a.printPreview=
"undefined"===typeof a.printPreview?!1:1===parseInt(a.printPreview,10)?!0:!1}},createChartContainer:function(a){var b=Pie[g],c=document.createElement("div");c.style.width=b.width+"px";c.style.height=b.height+"px";c.style.position="relative";c.style.padding="0";c.style.margin="0";c.style.top="0px";c.style.left="0px";a.appendChild(c);return c},getSize:function(a){var b=0,c=0,d=0,f=0,e=0,h=0;Pie[g].Render.isMobile.any()&&("undefined"!==typeof a.scrollWidth&&(b=a.scrollWidth),"undefined"!==typeof a.scrollHeight&&
(c=a.scrollHeight));"undefined"!==typeof a.offsetWidth&&(d=a.offsetWidth);"undefined"!==typeof a.offsetHeight&&(f=a.offsetHeight);"undefined"!==typeof a.clientWidth&&(e=a.clientWidth);"undefined"!==typeof a.clientHeight&&(h=a.clientHeight);return{width:Math.max(e,d,b),height:Math.max(h,f,c)}},deleteChilds:function(a){for(var b=a.childNodes,c=b.length;c--;)a.removeChild(b[c])},addEvent:function(a,b,c){if(a.addEventListener)return a.addEventListener(b,c,!1),!0;if(a.attachEvent)return a.attachEvent("on"+
b,c);a["on"+b]=c},ToolTip:{reference:null,visible:!1,initialize:function(){var a=Pie[g],b=a.params.xmlData.chart,c=document.getElementById("Pie-chart-"+g+"-tooltip-container");c||(c=document.createElement("div"),c.id="Pie-chart-"+g+"-tooltip-container");c.style.position="absolute";c.style.top="0px";c.style.left="0px";c.style.border=b.toolTipBorderWidth+"px solid #"+b.toolTipBorderColor;c.style.display="none";c.style.padding="3px 5px";c.style.background="#"+b.toolTipBgColor;c.style.fontFamily=b.toolTipFontFamily;
c.style.fontSize=b.toolTipFontSize+"px";c.style.color="#"+b.toolTipFontColor;c.style.boxShadow="2px 2px 3px #999999";c.style.zIndex="99999";document.getElementsByTagName("body")[0].appendChild(c);a.ToolTip.reference=c;a.addEvent(document,"mousemove",a.ToolTip.moveHandler)},moveHandler:function(a){if("undefined"!==typeof Pie[g]){var b=Pie[g];b.ToolTip.visible&&(a=a||window.event,b.ToolTip.moveToolTip(a))}},moveToolTip:function(a){if("undefined"!==typeof a){var b=Pie[g],c=0,d=0;a.pageX||a.pageY?(c=
a.pageX,d=a.pageY):(c=a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft)-document.documentElement.clientLeft,d=a.clientY+(document.documentElement.scrollTop||document.body.scrollTop)-document.documentElement.clientTop);b.ToolTip.reference.style.left=c+20+"px";b.ToolTip.reference.style.top=d+20+"px"}},show:function(a){var b=Pie[g];b.ToolTip.moveToolTip(window.event);b.deleteChilds(b.ToolTip.reference);null!==b.ToolTip&&(b.ToolTip.reference.innerHTML=a,b.ToolTip.reference.style.display=
"block",b.ToolTip.visible=!0)},hide:function(){var a=Pie[g];null!==a.ToolTip&&(a.ToolTip.visible=!1,a.ToolTip.reference.style.display="none")}},Render:{svgNS:"http://www.w3.org/2000/svg",render:null,androidDetected:!1,detectAndroid:function(){var a=navigator.userAgent.toLowerCase();Pie[g].Render.androidDetected=-1<a.indexOf("android")},isMobile:{Android:function(){return navigator.userAgent.match(/Android/i)?!0:!1},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)?!0:!1},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)?
!0:!1},Windows:function(){return navigator.userAgent.match(/IEMobile/i)?!0:!1},any:function(){var a=Pie[g].Render;return a.isMobile.Android()||a.isMobile.BlackBerry()||a.isMobile.iOS()||a.isMobile.Windows()}},supportsSVG:function(){return!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},supportsVML:function(){var a=document.body.appendChild(document.createElement("div"));a.innerHTML='<v:shape id="vml_flag1" adj="1" />';var b=a.firstChild;b.style.behavior=
"url(#default#VML)";b=b?"object"==typeof b.adj:!0;a.parentNode.removeChild(a);return b},supportsCanvas:function(){var a=document.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))},InitializeRender:function(){Pie[g].Render.detectAndroid();var a=Pie[g].Render.supportsSVG(),b=Pie[g].Render.supportsVML(),c=Pie[g].Render.supportsCanvas();if(a)Pie[g].Render.render="SVG";else if(b)Pie[g].Render.render="VML";else if(c)Pie[g].Render.render="Canvas";else throw Error("Not Found any supported renderer for Pie chart!");
}},NodeStore:{root:null,legendContainer:null,legendRectangle:null,documentFragmentRef:null},NodeFactory:{SVG:{innerOverlayGradient:null,outerOverlayGradient:null,mainCircleShadow:null,getSize:function(a,b){var c=Pie[g],d=document.createElement("div");d.style.position="absolute";d.style.top="0px";d.style.left="0px";d.style.fontFamily=b.font;d.style.fontSize=b.fontSize+"px";d.appendChild(document.createTextNode(a));c.params.container.appendChild(d);var f=c.getSize(d);c.params.container.removeChild(d);
return f},createRoot:function(){var a=Pie[g],b=document.createElementNS(a.Render.svgNS,"svg");a.NodeStore.documentFragmentRef=document.createDocumentFragment();a.NodeStore.documentFragmentRef.appendChild(b);b.setAttribute("width",a.width);b.setAttribute("height",a.height);a.NodeStore.root=b;a.NodeFactory.SVG.initGradients();a.NodeFactory.SVG.initShadows()},drawLogo:{init:function(){var a=Pie[g],b=a.NodeStore.root,c=a.width-130,d=a.height-50,f=""+parseInt(1073741824*Math.random(),10);a.NodeFactory.SVG.drawLogo.createGradient(b,
f,{cx:c+20,cy:d+20,radius:30});a.NodeFactory.SVG.drawLogo.drawCirclePart({angleStart:70,angleEnd:340,color:"url(#"+f+")",cx:c+20,cy:d+20,radius:20,container:b});a.NodeFactory.SVG.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+20+2,cy:d+20+1,radius:20,container:b});a.NodeFactory.SVG.drawLogo.createText(b,c+20+9,d+20+13)},logoHoverHandler:function(a){var b=Pie[g];b.addEvent(a,"mouseover",function(a){a.target.style.cursor="pointer"});b.addEvent(a,"click",function(){window.location.assign("http://www.hdcharts.com/")});
b.addEvent(a,"mouseout",function(a){a.target.style.cursor="default"})},drawPoly:function(a){var b=Pie[g],c=document.createElementNS(b.Render.svgNS,"path"),d,f=a.points,e=f.length-1;for(d="M"+(f[e].x+" "+f[e].y);e--;)d=d+"L"+f[e].x+" "+f[e].y;c.setAttribute("d",d+" z");c.setAttribute("fill",a.color);c.setAttribute("fill-opacity",a.opacity);a.container.appendChild(c);b.NodeFactory.SVG.drawLogo.logoHoverHandler(c)},drawCirclePart:function(a){var b=Pie[g],c=[],d=a.cx,f=a.cy,e=a.radius;c.push({x:d,y:f});
for(var h=a.angleStart;h<=a.angleEnd;h++){var k=h*(Math.PI/180),j=0,l=0,j=d+e*Math.cos(k),l=f+e*Math.sin(k);c.push({x:j,y:l})}b.NodeFactory.SVG.drawLogo.drawPoly({points:c,color:a.color,container:a.container})},createGradient:function(a,b,c){var d=Pie[g],f=document.createElementNS(d.Render.svgNS,"radialGradient");f.id=b;f.setAttribute("gradientUnits","userSpaceOnUse");f.setAttribute("cx",c.cx);f.setAttribute("cy",c.cy);f.setAttribute("r",c.radius);b=document.createElementNS(d.Render.svgNS,"stop");
b.setAttribute("offset","0%");b.setAttribute("stop-color","#5f5f5f");b.setAttribute("stop-opacity","100");f.appendChild(b);d=document.createElementNS(d.Render.svgNS,"stop");d.setAttribute("offset","100%");d.setAttribute("stop-color","#434343");d.setAttribute("stop-opacity","100");f.appendChild(d);a.appendChild(f)},createText:function(a,b,c){var d=Pie[g],f=document.createElementNS(d.Render.svgNS,"text");f.appendChild(document.createTextNode("HD"));f.style.fontFamily="Tahoma";f.style.fontSize="17px";
f.style.fontWeight="bold";f.setAttribute("fill","#434343");f.setAttribute("x",b);f.setAttribute("y",c);a.appendChild(f);d.NodeFactory.SVG.drawLogo.logoHoverHandler(f);f=document.createElementNS(d.Render.svgNS,"text");f.appendChild(document.createTextNode("CHARTS"));f.style.fontFamily="Tahoma";f.style.fontSize="17px";f.style.fontWeight="bold";f.setAttribute("fill","#F15A23");f.setAttribute("x",b+27);f.setAttribute("y",c);a.appendChild(f);d.NodeFactory.SVG.drawLogo.logoHoverHandler(f)}},initBackgroundGradient:function(a,
b,c){var d=Pie[g],f=d.params.xmlData.chart,e=document.createElementNS(d.Render.svgNS,"linearGradient");e.id="Pie-background-gradient-"+g+"-"+a+"-"+b+"-"+c;c=parseInt(c);switch(c){case 0:e.setAttribute("x1","0%");e.setAttribute("y1","100%");e.setAttribute("x2","0%");e.setAttribute("y2","0%");break;case 45:e.setAttribute("x1","100%");e.setAttribute("y1","100%");e.setAttribute("x2","0%");e.setAttribute("y2","0%");break;case 90:e.setAttribute("x1","100%");e.setAttribute("y1","0%");e.setAttribute("x2",
"0%");e.setAttribute("y2","0%");break;case 135:e.setAttribute("x1","100%");e.setAttribute("y1","0%");e.setAttribute("x2","0%");e.setAttribute("y2","100%");break;case 180:e.setAttribute("x1","0%");e.setAttribute("y1","0%");e.setAttribute("x2","0%");e.setAttribute("y2","100%");break;case 225:e.setAttribute("x1","0%");e.setAttribute("y1","0%");e.setAttribute("x2","100%");e.setAttribute("y2","100%");break;case 270:e.setAttribute("x1","0%");e.setAttribute("y1","0%");e.setAttribute("x2","100%");e.setAttribute("y2",
"0%");break;case 315:e.setAttribute("x1","0%");e.setAttribute("y1","100%");e.setAttribute("x2","100%");e.setAttribute("y2","0%");break;case 360:e.setAttribute("x1","0%"),e.setAttribute("y1","100%"),e.setAttribute("x2","0%"),e.setAttribute("y2","0%")}c=document.createElementNS(d.Render.svgNS,"stop");c.setAttribute("offset","0%");c.setAttribute("stop-color",a);c.setAttribute("stop-opacity",f.bgAlpha);e.appendChild(c);a=document.createElementNS(d.Render.svgNS,"stop");a.setAttribute("offset","100%");
a.setAttribute("stop-color",b);a.setAttribute("stop-opacity",f.bgAlpha);e.appendChild(a);d.NodeStore.root.appendChild(e);d.NodeFactory.SVG.backgroundGradient=e;return e.id},initGradients:function(){var a=Pie[g],b=document.createElementNS(a.Render.svgNS,"linearGradient");b.setAttribute("x1","0%");b.setAttribute("y1","0%");b.setAttribute("x2","0%");b.setAttribute("y2","100%");b.id="pie-chart-"+g+"-inner-overlay-gradient";a.NodeFactory.SVG.innerOverlayGradient="pie-chart-"+g+"-inner-overlay-gradient";
var c=document.createElementNS(a.Render.svgNS,"stop");c.setAttribute("offset","0%");c.setAttribute("stop-color","#FFFFFF");c.setAttribute("stop-opacity","0");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"stop");c.setAttribute("offset","100%");c.setAttribute("stop-color","#FFFFFF");c.setAttribute("stop-opacity","0.4");b.appendChild(c);a.NodeStore.root.appendChild(b);b=document.createElementNS(a.Render.svgNS,"linearGradient");b.setAttribute("x1","0%");b.setAttribute("y1","0%");b.setAttribute("x2",
"0%");b.setAttribute("y2","100%");b.id="pie-chart-"+g+"-outer-overlay-gradient";a.NodeFactory.SVG.outerOverlayGradient="pie-chart-"+g+"-outer-overlay-gradient";c=document.createElementNS(a.Render.svgNS,"stop");c.setAttribute("offset","0%");c.setAttribute("stop-color","#FFFFFF");c.setAttribute("stop-opacity","0.4");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"stop");c.setAttribute("offset","100%");c.setAttribute("stop-color","#FFFFFF");c.setAttribute("stop-opacity","0");b.appendChild(c);
a.NodeStore.root.appendChild(b)},initShadows:function(){var a=Pie[g],b=document.createElementNS(a.Render.svgNS,"filter");a.NodeFactory.SVG.mainCircleShadow="pie-chart-"+g+"-main-circle-shadow";b.setAttribute("id",a.NodeFactory.SVG.mainCircleShadow);b.setAttribute("x","-1");b.setAttribute("y","-1");b.setAttribute("width","250%");b.setAttribute("height","250%");var c=document.createElementNS(a.Render.svgNS,"feOffset");c.setAttribute("result","offOut");c.setAttribute("in","SourceGraphic");c.setAttribute("dx",
"2");c.setAttribute("dy","2");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"feColorMatrix");c.setAttribute("result","matrixOut");c.setAttribute("in","offOut");c.setAttribute("type","matrix");c.setAttribute("values","0.1 0 0 0 0 0 0.1 0 0 0 0 0 0.1 0 0 0 0 0 0.7 0");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"feGaussianBlur");c.setAttribute("result","blurOut");c.setAttribute("in","matrixOut");c.setAttribute("stdDeviation","2");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,
"feBlend");c.setAttribute("in","SourceGraphic");c.setAttribute("in2","blurOut");c.setAttribute("mode","normal");b.appendChild(c);a.NodeStore.root.appendChild(b)},createBackground:function(){var a=Pie[g],b=a.params.xmlData.chart,c=document.createElementNS(a.Render.svgNS,"rect");c.setAttribute("x",0);c.setAttribute("y",0);c.setAttribute("width",a.width);c.setAttribute("height",a.height);var d=b.bgColor.split(",");1==d.length?c.setAttribute("fill","#"+b.bgColor):(b=a.NodeFactory.SVG.initBackgroundGradient("#"+
d[0],"#"+d[1],b.bgAngle),c.setAttribute("fill","url(#"+b+")"));a.NodeStore.root.appendChild(c)},drawLegendBackground:function(a){var b=Pie[g],c=b.params.xmlData.chart,d=document.createElementNS(b.Render.svgNS,"rect");d.setAttribute("filter","url(#"+b.NodeFactory.SVG.mainCircleShadow+")");d.setAttribute("x",a.x);d.setAttribute("y",a.y);d.setAttribute("width",a.w);d.setAttribute("height",a.h);d.setAttribute("stroke","#"+c.legendBorderColor.replace("#",""));d.setAttribute("stroke-width",c.legendBorderWidth+
"px");c=a.color.split(",");1==c.length?d.setAttribute("fill","#"+a.color):(a=b.NodeFactory.SVG.initBackgroundGradient("#"+c[0],"#"+c[1],a.angle),d.setAttribute("fill","url(#"+a+")"));b.NodeStore.root.appendChild(d);b.NodeStore.legendRectangle=d},drawPoly:function(a){for(var b=Pie[g],c=b.params.xmlData.chart,d=document.createElementNS(b.Render.svgNS,"path"),f="M",e=a.points,h=e.length-1,k=new b.Base.polyHoverHandler(a.tooltip),j=new b.Base.polyOutHandler,f=f+(e[h].x+" "+e[h].y);h--;)f=f+"L"+e[h].x+
" "+e[h].y;d.setAttribute("d",f+" z");d.setAttribute("fill","#"+a.color);d.setAttribute("fill-opacity",a.opacity);""!==a.url&&"undefined"!==typeof a.url&&(d.style.cursor="pointer",b.addEvent(d,"click",function(){window.open(a.url,"_blank")}));a.stroke&&("default"===c.borderColor?(d.setAttribute("stroke-width","1"),d.setAttribute("stroke-opacity",a.opacity),d.setAttribute("stroke","#"+a.color)):(d.setAttribute("stroke-width",c.borderWidth),d.setAttribute("stroke-opacity",a.opacity),d.setAttribute("stroke",
"#"+c.borderColor)));a.shadow&&d.setAttribute("filter","url(#"+b.NodeFactory.SVG.mainCircleShadow+")");b.NodeStore.root.appendChild(d);d.setOpacity=function(a){d.setAttribute("fill-opacity",a)};!1!==a.tooltip?(b.addEvent(d,"mouseover",k),b.addEvent(d,"mouseout",j)):(delete k,delete j)},drawOverlay:function(a){var b=Pie[g],c=[],d=b.NodeFactory.SVG.innerOverlayGradient;"outer"===a.type&&(d=b.NodeFactory.SVG.outerOverlayGradient);if(0!=a.innerRadius){for(var f=0;360>=f;f++){var e=b.degToRad(f),h=0,k=
0,h=a.x+a.innerRadius*Math.cos(e),k=a.y+a.innerRadius*Math.sin(e);c.push({x:h,y:k})}for(f=360;0<=f;f--)e=b.degToRad(f),h=a.x+a.outerRadius*Math.cos(e),k=a.y+a.outerRadius*Math.sin(e),c.push({x:h,y:k});f=document.createElementNS(b.Render.svgNS,"path");e=c.length-1;for(a="M"+(c[e].x+" "+c[e].y);e--;)a=a+"L"+c[e].x+" "+c[e].y;f.setAttribute("d",a+" z")}else f=document.createElementNS(b.Render.svgNS,"circle"),f.setAttribute("cx",a.x),f.setAttribute("cy",a.y),f.setAttribute("r",a.outerRadius);f.setAttribute("fill",
"url(#"+d+")");b.NodeStore.root.appendChild(f)},addStylesToTextObject:function(a,b){a.style.fontFamily=b.font;a.style.fontSize=b.size+"px";"1"==b.bold&&(a.style.fontWeight="bold");a.setAttribute("fill","#"+b.color)}},VML:{scaleCoefficient:100,precalculateValue:function(a,b){return parseInt(a*b,10)},createNode:null,createRoot:function(){var a=Pie[g];try{document.createStyleSheet().addRule(".rvml","behavior:url(#default#VML) ")}catch(b){}try{document.namespaces.add("rvml","urn:schemas-microsoft-com:vml"),
a.NodeFactory.VML.createNode=function(a,b){var c=document.createElement("<rvml:"+a+' class="rvml" >');"undefined"===typeof b&&(b=!1);if(b){var d=document.createElement('<rvml:stroke class="rvml" >');d.setAttribute("opacity","0%");c.appendChild(d)}return c}}catch(c){a.NodeFactory.VML.createNode=function(a,b){var c=document.createElement("<"+a+' xmlns="urn:schemas-microsoft.com:vml" class="rvml" >');"undefined"===typeof b&&(b=!1);if(b){var d=document.createElement('<rvml:stroke xmlns="urn:schemas-microsoft.com:vml" class="rvml" >');
d.setAttribute("opacity","0%");c.appendChild(d)}return c}}var d=document.createElement("div");d.style.width=a.width+"px";d.style.height=a.height+"px";a.NodeStore.documentFragmentRef=document.createDocumentFragment();a.NodeStore.documentFragmentRef.appendChild(d);a.NodeStore.root=d},drawLogo:{init:function(){var a=Pie[g],b=a.NodeStore.root,c=a.width-130,d=a.height-50,f=""+parseInt(1073741824*Math.random(),10);a.NodeFactory.VML.drawLogo.createGradient(b,f,{cx:c+5,cy:d+5,radius:30});a.NodeFactory.VML.drawLogo.drawCirclePart({angleStart:70,
angleEnd:340,color:"#434343",cx:c+5,cy:d+5,radius:20,container:b});a.NodeFactory.VML.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+5+2,cy:d+5+1,radius:20,container:b});a.NodeFactory.VML.drawLogo.createText(b,c+5+9,d+5+13)},logoHoverHandler:function(a){var b=Pie[g];b.addEvent(a,"mouseover",function(a){a.toElement.style.cursor="pointer"});b.addEvent(a,"click",function(){window.location.assign("http://www.hdcharts.com/")});b.addEvent(a,"mouseout",function(a){a.toElement.style.cursor=
"default"})},drawPoly:function(a){var b=Pie[g],c=b.NodeFactory.VML.createNode("shape");c.setAttribute("coordsize",b.NodeFactory.VML.precalculateValue(b.width,b.NodeFactory.VML.scaleCoefficient)+" "+b.NodeFactory.VML.precalculateValue(b.height,b.NodeFactory.VML.scaleCoefficient));c.setAttribute("coordorigin","0 0");c.setAttribute("fillcolor",a.color);c.style.position="absolute";c.style.left="0 px";c.style.top="0 px";c.style.width=b.width+"px";c.style.height=b.height+"px";var d,f=a.points,e=f.length-
1,h=b.NodeFactory.VML.scaleCoefficient;for(d="M"+(parseInt(f[e].x*h,10)+" "+parseInt(f[e].y*h,10));e--;)d=d+"L"+parseInt(f[e].x*h,10)+" "+parseInt(f[e].y*h,10);d+=" z";f=b.NodeFactory.VML.createNode("path");f.setAttribute("v",d);c.appendChild(f);d=b.NodeFactory.VML.createNode("stroke");d.setAttribute("opacity",a.opacity);d.setAttribute("color",a.color);c.appendChild(d);a.container.appendChild(c);b.NodeFactory.VML.drawLogo.logoHoverHandler(c)},drawCirclePart:function(a){var b=Pie[g],c=[],d=a.cx,f=
a.cy,e=a.radius;c.push({x:d,y:f});for(var h=a.angleStart;h<=a.angleEnd;h++){var k=h*(Math.PI/180),j=0,l=0,j=d+e*Math.cos(k),l=f+e*Math.sin(k);c.push({x:j,y:l})}b.NodeFactory.VML.drawLogo.drawPoly({points:c,color:a.color,container:a.container})},createGradient:function(){},createText:function(a,b,c){var d=Pie[g],f="",f="m 0,0 l 1,0 e",e=d.NodeFactory.VML.createNode("shape",!0);e.style.position="absolute";e.style.top=c-3+"px";e.style.left=b+15+"px";e.style.zIndex=0;e.style.width="1px";e.style.height=
"1px";e.setAttribute("filled","t");e.setAttribute("fillcolor","#434343");e.setAttribute("stroked","f");e.setAttribute("path",f);var h=d.NodeFactory.VML.createNode("textpath");h.style.fontFamily="Tahoma";h.style.fontSize="17px";h.style.fontWeight="bold";h.setAttribute("fill","#434343");h.setAttribute("on","t");h.setAttribute("string","HD");e.appendChild(h);h=d.NodeFactory.VML.createNode("path");h.setAttribute("textpathok","t");e.appendChild(h);a.appendChild(e);d.NodeFactory.VML.drawLogo.logoHoverHandler(e);
e=d.NodeFactory.VML.createNode("shape",!0);e.style.position="absolute";e.style.top=c-3+"px";e.style.left=b+63+"px";e.style.zIndex=0;e.style.width="1px";e.style.height="1px";e.setAttribute("filled","t");e.setAttribute("fillcolor","#434343");e.setAttribute("stroked","f");e.setAttribute("path",f);h=d.NodeFactory.VML.createNode("textpath");h.style.fontFamily="Tahoma";h.style.fontSize="17px";h.style.fontWeight="bold";h.setAttribute("fill","#F15A23");h.setAttribute("on","t");h.setAttribute("string","CHARTS");
e.appendChild(h);h.setAttribute("x",b+27);h.setAttribute("y",c);h=d.NodeFactory.VML.createNode("path");h.setAttribute("textpathok","t");e.appendChild(h);a.appendChild(e);d.NodeFactory.VML.drawLogo.logoHoverHandler(e)}},createBackground:function(){var a=Pie[g],b=a.params.xmlData.chart,c=a.NodeFactory.VML.createNode("rect");c.style.top="-1px";c.style.left="-1px";c.style.width=a.width+1+"px";c.style.height=a.height+1+"px";c.style.border="0px";c.style.position="absolute";c.style.filter="alpha(opacity="+
b.bgAlpha+")";var d=b.bgColor.split(",");if(1==d.length){var f=a.NodeFactory.VML.createNode("fill");f.setAttribute("Color","#"+b.bgColor)}else f=a.NodeFactory.VML.createNode("fill"),f.setAttribute("Type","Gradient"),f.setAttribute("Angle",b.bgAngle),f.setAttribute("Color","#"+d[0]),f.setAttribute("Color2","#"+d[1]),f.setAttribute("Focus","0%"),f.setAttribute("method","none");c.appendChild(f);b=a.NodeFactory.VML.createNode("stroke");b.setAttribute("color","none");c.appendChild(b);a.NodeStore.root.appendChild(c)},
drawPoly:function(a){var b=Pie[g],c=b.params.xmlData.chart,d=b.NodeFactory.VML.createNode("shape",!a.stroke),f={pie:d,color:a.color,opacity:a.opacity};d.style.position="absolute";d.style.top="0px";d.style.left="0px";d.style.width=b.width+"px";d.style.height=b.height+"px";""!==a.url&&(d.style.cursor="pointer",b.addEvent(d,"click",function(){window.open(a.url,"_blank")}));for(var e="m ",h=a.points,k=h.length-1,j=b.NodeFactory.VML.precalculateValue(h[k].x,b.NodeFactory.VML.scaleCoefficient),l=b.NodeFactory.VML.precalculateValue(h[k].y,
b.NodeFactory.VML.scaleCoefficient),e=e+(j+","+l)+" l ";k--;)j=b.NodeFactory.VML.precalculateValue(h[k].x,b.NodeFactory.VML.scaleCoefficient),l=b.NodeFactory.VML.precalculateValue(h[k].y,b.NodeFactory.VML.scaleCoefficient),e=e+j+","+l+", ";e+=" x e";d.setAttribute("coordorigin","0 0");d.setAttribute("coordsize",b.width*b.NodeFactory.VML.scaleCoefficient+","+b.height*b.NodeFactory.VML.scaleCoefficient);d.setAttribute("path",e);e=b.NodeFactory.VML.createNode("fill");e.setAttribute("Color","#"+a.color);
e.setAttribute("opacity",a.opacity);a.stroke&&("default"===c.borderColor?(d.setAttribute("strokeweight",parseInt(c.borderWidth,10)),d.setAttribute("stroke-opacity","alpha(opacity="+100*a.opacity+")"),d.setAttribute("strokecolor","#"+a.color)):(d.setAttribute("strokeweight",parseInt(c.borderWidth,10)),d.setAttribute("stroke-opacity","alpha(opacity="+100*a.opacity+")"),d.setAttribute("strokecolor","#"+c.borderColor)));a.shadow&&parseInt(a.opacity)&&(c=b.NodeFactory.VML.createNode("shadow"),c.setAttribute("on",
"true"),c.setAttribute("type","single"),c.setAttribute("obscured","false"),c.setAttribute("color","rgb(128,128,128)"),c.setAttribute("opacity","1.0"),c.setAttribute("offset","2pt,2pt"),c.setAttribute("color2","rgb(203,203,203)"),c.setAttribute("opacity2","1.0"),c.setAttribute("offset2","0pt,0pt"),c.setAttribute("origin","0,0"),c.setAttribute("matrix","null"),d.appendChild(c));d.appendChild(e);b.NodeStore.root.appendChild(d);c=new b.Base.polyHoverHandler(a.tooltip,f);f=new b.Base.polyOutHandler(f);
!1!==a.tooltip?(b.addEvent(d,"mouseover",c),b.addEvent(d,"mouseout",f)):(delete c,delete f)},drawOverlay:function(a){var b=Pie[g],c=[];if(0!=a.innerRadius){for(var d=0;360>=d;d++){var f=b.degToRad(d),e=0,h=0,e=a.x+a.innerRadius*Math.cos(f),h=a.y+a.innerRadius*Math.sin(f);c.push({x:e,y:h})}for(d=360;0<=d;d--)f=b.degToRad(d),e=a.x+a.outerRadius*Math.cos(f),h=a.y+a.outerRadius*Math.sin(f),c.push({x:e,y:h});d=b.NodeFactory.VML.createNode("shape");d.style.position="absolute";d.style.top="0px";d.style.left=
"0px";d.style.width=b.width+"px";d.style.height=b.height+"px";for(var f="m ",k=c.length-1,e=b.NodeFactory.VML.precalculateValue(c[k].x,b.NodeFactory.VML.scaleCoefficient),h=b.NodeFactory.VML.precalculateValue(c[k].y,b.NodeFactory.VML.scaleCoefficient),f=f+(e+","+h+" l ");k--;)e=b.NodeFactory.VML.precalculateValue(c[k].x,b.NodeFactory.VML.scaleCoefficient),h=b.NodeFactory.VML.precalculateValue(c[k].y,b.NodeFactory.VML.scaleCoefficient),f=f+e+","+h+", ";f+=" x e";d.setAttribute("coordorigin","0 0");
d.setAttribute("coordsize",b.width*b.NodeFactory.VML.scaleCoefficient+","+b.height*b.NodeFactory.VML.scaleCoefficient);d.setAttribute("path",f);d.setAttribute("strokeweight","0");c=document.createElement('<fill xmlns="urn:schemas-microsoft-com:office:office" class="rvml" >');c.setAttribute("type","gradient");c.setAttribute("Color","#ffffff");c.setAttribute("opacity","0.5");c.setAttribute("o:opacity2","0");d.appendChild(c);"outer"===a.type&&(c.setAttribute("opacity","0"),c.setAttribute("o:opacity2",
"0.5"));a=b.NodeFactory.VML.createNode("stroke");a.setAttribute("opacity","0");d.appendChild(a);b.NodeStore.root.appendChild(d)}},drawLegendBackground:function(a){var b=Pie[g],c=b.NodeFactory.VML.createNode("rect"),d=b.params.xmlData.chart;c.style.top=a.y+"px";c.style.left=a.x+"px";c.style.width=a.w+"px";c.style.height=a.h+"px";c.style.position="absolute";var f=a.color.split(",");if(1==f.length)c.setAttribute("fillcolor","#"+a.color);else{var e=b.NodeFactory.VML.createNode("fill");e.setAttribute("Type",
"Gradient");e.setAttribute("Angle",a.angle);e.setAttribute("Color","#"+f[0]);e.setAttribute("Color2","#"+f[1]);e.setAttribute("Focus","0%");e.setAttribute("method","none");c.appendChild(e)}a=b.NodeFactory.VML.createNode("stroke");a.setAttribute("color","#"+d.legendBorderColor);a.setAttribute("weight",d.legendBorderWidth+"px");c.appendChild(a);b.NodeStore.root.appendChild(c);d=b.NodeFactory.VML.createNode("shadow");d.setAttribute("on","true");d.setAttribute("type","single");d.setAttribute("obscured",
"false");d.setAttribute("color","rgb(128,128,128)");d.setAttribute("opacity","1.0");d.setAttribute("offset","2pt,2pt");d.setAttribute("color2","rgb(203,203,203)");d.setAttribute("opacity2","1.0");d.setAttribute("origin","0,0");d.setAttribute("matrix","null");c.appendChild(d);b.NodeStore.legendRectangle=c},addStylesToTextObject:function(a,b){a.style.fontFamily=b.font;a.style.fontSize=b.size+"px";a.style.color="#"+b.color;"1"==b.bold&&(a.style.fontWeight="bold");a.setAttribute("fillcolor","#"+b.color)}},
Canvas:{createNode:null,mainCircleShadow:null,innerOverlayGradient:null,outerOverlayGradient:null,getSize:function(a,b){var c=Pie[g],d=document.createElement("div");d.style.position="absolute";d.style.top="0px";d.style.left="0px";d.style.fontFamily=b.font;d.style.fontSize=b.fontSize+"px";d.appendChild(document.createTextNode(a));c.params.container.appendChild(d);var f=c.getSize(d);c.params.container.removeChild(d);return f},createRoot:function(){var a=Pie[g],b=document.createElement("canvas");b.setAttribute("width",
a.width);b.setAttribute("height",a.height);a.chartContainer.appendChild(b);a.NodeStore.root=b.getContext("2d");a.NodeFactory.Canvas.initGradients()},drawLogo:{innerOverlayGradient:null,outerOverlayGradient:null,init:function(){var a=Pie[g],b=a.NodeStore.root,c=a.width-130,d=a.height-50,f=""+parseInt(1073741824*Math.random(),10);a.NodeFactory.Canvas.drawLogo.createGradient(b,f,{cx:c+20,cy:d+20,radius:30});a.NodeFactory.Canvas.drawLogo.drawCirclePart({angleStart:70,angleEnd:340,color:a.NodeFactory.Canvas.drawLogo.outerOverlayGradient,
cx:c+20,cy:d+20,radius:20,container:b});a.NodeFactory.Canvas.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+20+2,cy:d+20+1,radius:20,container:b});a.NodeFactory.Canvas.drawLogo.createText(b,c+20+9,d+20+13)},drawPoly:function(a){var b=Pie[g].NodeStore.root,c=a.points,d=c.length-1;b.globalAlpha=1;b.save();b.beginPath();for(b.moveTo(c[d].x,c[d].y);d--;)b.lineTo(c[d].x,c[d].y);b.fillStyle=a.color;b.lineWidth=1;b.closePath();b.fill();b.globalAlpha=1;b.restore()},drawCirclePart:function(a){var b=
Pie[g],c=[],d=a.cx,f=a.cy,e=a.radius;c.push({x:d,y:f});for(var h=a.angleStart;h<=a.angleEnd;h++){var k=h*(Math.PI/180),j=0,l=0,j=d+e*Math.cos(k),l=f+e*Math.sin(k);c.push({x:j,y:l})}b.NodeFactory.Canvas.drawLogo.drawPoly({points:c,color:a.color,container:a.container})},createGradient:function(a,b,c){a=Pie[g];var d=a.NodeStore.root;b=d.createLinearGradient(0,0,0,a.height);c=d.createRadialGradient(c.cx,c.cy,0,c.cx,c.cy,30);b.addColorStop(0,"rgba(255,255,255,0.0)");b.addColorStop(1,"rgba(255,255,255,0.4)");
c.addColorStop(0,"rgba(0,0,0,0.5)");c.addColorStop(1,"rgba(0,0,0,0.5)");a.NodeFactory.Canvas.drawLogo.innerOverlayGradient=b;a.NodeFactory.Canvas.drawLogo.outerOverlayGradient=c},createText:function(a,b,c){a=Pie[g].NodeStore.root;var d="Tahoma",f="15",e="434343";a.save();a.font=f+"px  "+d+" bold";a.fillStyle="#"+e;a.textAlign="center";a.translate(b+10,c);a.fillText("HD",0,0);a.restore();d="Tahoma";f="15";e="F15A23";a.save();a.font=f+"px  "+d+" bold";a.fillStyle="#"+e;a.textAlign="center";a.translate(b+
52,c);a.fillText("CHARTS",0,0);a.restore()}},initBackgroundGradient:function(a,b,c){var d=Pie[g],f=d.NodeStore.root;c=parseInt(c,10);switch(c){case 0:var e=f.createLinearGradient(0,d.height,0,0);break;case 45:e=f.createLinearGradient(d.width,d.height,0,0);break;case 90:e=f.createLinearGradient(d.width,0,0,0);break;case 135:e=f.createLinearGradient(d.width,0,0,d.height);break;case 180:e=f.createLinearGradient(0,0,0,d.height);break;case 225:e=f.createLinearGradient(0,0,d.width,d.height);break;case 270:e=
f.createLinearGradient(0,0,d.width,0);break;case 315:e=f.createLinearGradient(0,d.height,d.width,0);break;case 360:e=f.createLinearGradient(0,d.height,0,0)}e.addColorStop(0,a);e.addColorStop(1,b);return e},initGradients:function(){var a=Pie[g],b=a.NodeStore.root,c=b.createLinearGradient(0,0,0,a.height),b=b.createLinearGradient(0,0,0,a.height);c.addColorStop(0,"rgba(255,255,255,0.0)");c.addColorStop(1,"rgba(255,255,255,0.4)");b.addColorStop(0,"rgba(255,255,255,0.5)");b.addColorStop(1,"rgba(255,255,255,0.0)");
a.NodeFactory.Canvas.innerOverlayGradient=c;a.NodeFactory.Canvas.outerOverlayGradient=b},initShadows:function(){var a=Pie[g];a.Render.androidDetected||(a=a.NodeStore.root,a.shadowOffsetY=3,a.shadowOffsetX=3,a.shadowBlur=2,a.shadowColor="rgb(84,84,84)")},createBackground:function(){var a=Pie[g],b=a.params.xmlData.chart,c=a.NodeStore.root;c.beginPath();c.rect(0,0,a.width,a.height);var d=b.bgColor.split(",");1==d.length?c.fillStyle="#"+b.bgColor:(a=a.NodeFactory.Canvas.initBackgroundGradient("#"+d[0],
"#"+d[1],b.bgAngle),c.fillStyle=a);c.closePath();c.globalAlpha=b.bgAlpha/100;c.fill();c.globalAlpha=1},drawLegendBackground:function(a){var b=Pie[g],c=b.NodeStore.root,d=b.params.xmlData.chart;c.save();c.beginPath();c.rect(a.x,a.y,a.w,a.h);var f=a.color.split(",");1==f.length?c.fillStyle="#"+a.color:(a=b.NodeFactory.Canvas.initBackgroundGradient("#"+f[0],"#"+f[1],a.angle),c.fillStyle=a,b.NodeFactory.Canvas.initShadows());c.closePath();c.fill();c.lineWidth=d.legendBorderWidth;c.strokeStyle="#"+d.legendBorderColor;
c.stroke();c.restore();c.shadowOffsetX=0;c.shadowOffsetY=0;c.shadowBlur=0;c.shadowColor="rgba(0,0,0,0.0)"},drawPoly:function(a){var b=Pie[g],c=b.NodeStore.root,b=b.params.xmlData.chart,d=a.points,f=d.length-1;c.save();c.beginPath();for(c.moveTo(d[f].x,d[f].y);f--;)c.lineTo(d[f].x,d[f].y);c.fillStyle="#"+a.color;c.globalAlpha=a.opacity;a.stroke&&("default"===b.borderColor?(c.lineWidth=1,c.strokeStyle="#"+a.color):(c.lineWidth=b.borderWidth,c.strokeStyle="#"+b.borderColor));c.closePath();c.fill();a.stroke&&
c.stroke();c.globalAlpha=1;c.restore()},drawOverlay:function(a){var b=Pie[g],c=[],d=b.NodeFactory.Canvas.innerOverlayGradient,f=b.NodeStore.root;"outer"===a.type&&(d=b.NodeFactory.Canvas.outerOverlayGradient);if(0!=a.innerRadius){for(var e=0;360>=e;e++){var h=b.degToRad(e),k=0,j=0,k=a.x+a.innerRadius*Math.cos(h),j=a.y+a.innerRadius*Math.sin(h);c.push({x:k,y:j})}for(e=360;0<=e;e--)h=b.degToRad(e),k=a.x+a.outerRadius*Math.cos(h),j=a.y+a.outerRadius*Math.sin(h),c.push({x:k,y:j});a=c.length-1;f.save();
f.beginPath();for(f.moveTo(c[a].x,c[a].y);a--;)f.lineTo(c[a].x,c[a].y)}else f.save(),f.beginPath(),ctx.arc(a.x,a.y,a.outerRadius,0,2*Math.PI,!0);f.fillStyle=d;f.closePath();f.fill();f.restore()},addStylesToTextObject:function(a){var b=Pie[g].NodeStore.root,c="",c="undefined"!==typeof a.italic?"1"==a.italic?c+"italic ":c+"normal ":c+"normal ",c="undefined"!==typeof a.bold?"1"==a.bold?c+"bold ":c+"normal ":c+"normal ",c="undefined"===typeof a.size?c+"11px ":c+a.size+"px ",c="undefined"===typeof a.font?
c+"Tahoma ":c+a.font;b.font=c;b.fillStyle="undefined"!==typeof a.color?"#"+a.color:"#000000"}}}};return{width:0,height:0,chart:window.Pie[g],data:n,initialize:function(a,b){window.Pie[g].initialize(a,b);this.width=a;this.height=b},redraw:function(a){"undefined"===typeof a?a=this.data:this.data=a;window.Pie[g].initialize(this.width,this.height,a)}}}throw Error("PieChart Error: Incorect data passed to PieChart ( container, jsData, chartId )!");}
function PieChartXML(p,n,g){if("undefined"!==typeof p&&null!=p&&"undefined"!==typeof n){var q=function(a){var c=null;if(window.DOMParser)try{c=(new DOMParser).parseFromString(a,"text/xml")}catch(d){c=null}else if(window.ActiveXObject)try{if(c=new ActiveXObject("Microsoft.XMLDOM"),c.async=!1,!c.loadXML(a))throw Error(c.parseError.reason+c.parseError.srcText);}catch(f){c=null}else throw Error("cannot parse xml string!");return c},a=function(a){var c={toObj:function(a){var b={};if(1==a.nodeType){if(a.attributes.length)for(var e=
0;e<a.attributes.length;e++)b[a.attributes[e].nodeName]=(a.attributes[e].nodeValue||"").toString();if(a.firstChild){for(var h=e=0,g=!1,j=a.firstChild;j;j=j.nextSibling)1==j.nodeType?g=!0:3==j.nodeType&&j.nodeValue.match(/[^ \f\n\r\t\v]/)?e++:4==j.nodeType&&h++;if(g)if(2>e&&2>h){c.removeWhite(a);for(j=a.firstChild;j;j=j.nextSibling)3==j.nodeType?b["#text"]=c.escape(j.nodeValue):4==j.nodeType?b["#cdata"]=c.escape(j.nodeValue):b[j.nodeName]?b[j.nodeName]instanceof Array?b[j.nodeName][b[j.nodeName].length]=
c.toObj(j):b[j.nodeName]=[b[j.nodeName],c.toObj(j)]:b[j.nodeName]=c.toObj(j)}else a.attributes.length?b["#text"]=c.escape(c.innerXml(a)):b=c.escape(c.innerXml(a));else if(e)a.attributes.length?b["#text"]=c.escape(c.innerXml(a)):b=c.escape(c.innerXml(a));else if(h)if(1<h)b=c.escape(c.innerXml(a));else for(j=a.firstChild;j;j=j.nextSibling)b["#cdata"]=c.escape(j.nodeValue)}!a.attributes.length&&!a.firstChild&&(b=null)}else 9==a.nodeType?b=c.toObj(a.documentElement):alert("unhandled node type: "+a.nodeType);
return b},toJson:function(a,b,e){var h=b?'"'+b+'"':"";if(a instanceof Array){for(var g=0,j=a.length;g<j;g++)a[g]=c.toJson(a[g],"",e+"\t");h+=(b?":[":"[")+(1<a.length?"\n"+e+"\t"+a.join(",\n"+e+"\t")+"\n"+e:a.join(""))+"]"}else if(null==a)h+=(b&&":")+"null";else if("object"==typeof a){g=[];for(j in a)g[g.length]=c.toJson(a[j],j,e+"\t");h+=(b?":{":"{")+(1<g.length?"\n"+e+"\t"+g.join(",\n"+e+"\t")+"\n"+e:g.join(""))+"}"}else h="string"==typeof a?h+((b&&":")+'"'+a.toString()+'"'):h+((b&&":")+a.toString());
return h},innerXml:function(a){var b="";if("innerHTML"in a)b=a.innerHTML;else{var c=function(a){var b="";if(1==a.nodeType){for(var b=b+("<"+a.nodeName),d=0;d<a.attributes.length;d++)b+=" "+a.attributes[d].nodeName+'="'+(a.attributes[d].nodeValue||"").toString()+'"';if(a.firstChild){b+=">";for(d=a.firstChild;d;d=d.nextSibling)b+=c(d);b+="</"+a.nodeName+">"}else b+="/>"}else 3==a.nodeType?b+=a.nodeValue:4==a.nodeType&&(b+="<![CDATA["+a.nodeValue+"]]\x3e");return b};for(a=a.firstChild;a;a=a.nextSibling)b+=
c(a)}return b},escape:function(a){return a.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(a){a.normalize();for(var b=a.firstChild;b;)if(3==b.nodeType)if(b.nodeValue.match(/[^ \f\n\r\t\v]/))b=b.nextSibling;else{var e=b.nextSibling;a.removeChild(b);b=e}else 1==b.nodeType&&c.removeWhite(b),b=b.nextSibling;return a}};9==a.nodeType&&(a=a.documentElement);return"{\n"+c.toJson(c.toObj(c.removeWhite(a)),a.nodeName,"\t").replace(/\t|\n/g,
"")+"\n}"};return{parseXml:q,XMLtoJSON:a,xmlStr:n,chart:null,container:p,symbols:[{symbol:/!#amp!/g,replacement:"&"},{symbol:/%26lt;/g,replacement:"<"},{symbol:/%26gt;/g,replacement:">"}],encodeString:function(a){for(var c=this.symbols,d=c.length;d--;)a=a.replace(c[d].symbol,c[d].replacement);return a},getParamsFromXML:function(b){b=b.replace(/&/g,"!#amp!");b=q(b);b=a(b);b=this.encodeString(b);b=eval("("+b+")");var c={};if("undefined"!==typeof b.parsererror)throw Error("XML parse error in PieChart lib!");
c.xmlData=b;c.container=this.container;return c},initialize:function(a,c){var d=this.getParamsFromXML(this.xmlStr),d=new PieChart(p,d,g);d.initialize(a,c);this.chart=d},redrawXML:function(a){a=this.getParamsFromXML(a);this.chart.redraw(a)}}}throw Error("PieChart Error: Incorrect parameters passed to PieChartXML ( container, xmlStr )!");};