
/*

-- =============================================
-- Author:		Evgeni Yordanov, Alexandrina Ivanova
-- Create date: 2013-03-11
-- Description:	Trend chart JavaScript library. It uses SVG/VML/Canvas rendering to display the chart.
-- Version: 1.0
-- =============================================


	USE LICENSE
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on Research Metrics, LLC's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
			- modify or copy the materials;
			- use the materials for any commercial purpose, or for any public display (commercial or non-commercial);
			- attempt to decompile or reverse-engineer any software contained on Research Metrics, LLC's web site;
			- remove any copyright or other proprietary notations from the materials; or
			- transfer the materials to another person or "mirror" the materials on any other server.
		This license shall automatically be terminated if you violate any of these restrictions, and may be terminated by Research Metrics, LLC at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	
	DISCLAIMER
		The materials on Research Metrics, LLC's web site are provided "as is". Research Metrics, LLC makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Research Metrics, LLC does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	
	LIMITATIONS
	In no event shall Research Metrics, LLC or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Research Metrics, LLC's Internet site, even if Research Metrics, LLC or a Research Metrics, LLC authorized representative has been notified orally or in writing of the possibility of a such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
	
	GOVERNING LAW
	Any claim relating to Research Metrics, LLC's web site shall be governed by the laws of the State of Perrysburgs without regard to its conflict of law provisions.

*/


function TrendChart(s,n,k){if("undefined"!==typeof s&&"object"===typeof n){"undefined"===typeof window.Trend&&(window.Trend={});if("undefined"===typeof k){for(var v=0;"undefined"!==typeof Trend[v];)v++;k=v}window.Trend[k]={width:0,height:0,params:n,container:s,chartContainer:null,initialize:function(a,b,c){var e=Trend[k];if("undefined"===typeof n.xmlData&&"undefined"===typeof n.container){var f={xmlData:{chart:n},container:e.container};n=f;e.params=f}n.xmlData.chart=e.dataProxy.changeDataFormat(n.xmlData.chart);
"undefined"!==typeof c&&(n=c,e.params=n);if(e.ParamsChecker.checkParams(n))a=e.ParamsChecker.getSizeFromParams(a,b,e.container),e.width=a.width,e.height=a.height,e.Render.InitializeRender(),a=e.NodeFactory[e.Render.render],e.deleteChilds(e.container),b=e.createChartContainers(e.container),e.chartContainer=b.chartContainer,e.relativeContainer=b.relativeContainer,"complete"===document.readyState?e.ToolTip.initialize():e.addEvent(window,"load",function(){e.ToolTip.initialize()}),e.Base.drawCaption(),
e.Base.initBaseParams(),a.createRoot(),e.Base.createBackground(),e.Base.drawChartsPlace(),e.Base.drawLegendBackground(),e.Base.drawTrendZones(),e.Base.drawTrendLines(),e.Base.appendDocumentRef(),e.Base.drawLogo();else throw Error("Incorrect parameters passed to Trend Chart initialization!");},dataProxy:{changeDataFormat:function(a){var b={};if("undefined"!==typeof a.data){for(var c in a)if("data"!==c&&"categories"!==c&&"styles"!==c&&"trendLines"!==c)for(var e in a[c])"rotateCategoryNames"===e?b.rotateNames=
a[c][e]:"numDivLines"===e?b.numdivlines=a[c][e]:"showAxisHeadingsOnHover"===e?b.headingsHover=a[c][e]:b[e]=a[c][e];else"data"===c?b.dataset=a[c]:"categories"===c||"styles"===c?b[c]=a[c]:"trendLines"===c&&(b.trendLines=a[c]);return b}if("object"===typeof a.dataset)return a}},degToRad:function(a){return a*(Math.PI/180)},Base:{legendContainer:null,titleHeight:20,leftLabelsWidth:0,bottomLabelsHeight:0,bottomLabelsOffset:4,bottomLabelsPadding:2,titleBottomSpacing:4,leftLabelsOffset:3,shadowOffset:4,legendSidePadding:3,
legendMaxWidthCoef:0.75,shadowWidthCoef:1.5,shadowOpacity:30,anchorLabelOffset:12,legendMaxHeightCoef:0.3,colorDefaultVault:{colorArrayLight:"fadb7b D3EAFB BFD973 FFC199 73C1C1 E89999 C199C1 A3BC88 D5D073 73C1E8 cbbcdb c9777a".split(" "),validationObj:{1:!0,2:!0,3:!0,4:!0,5:!0,6:!0,7:!0,8:!0,9:!0,"0":!0,a:!0,b:!0,c:!0,d:!0,e:!0,f:!0,A:!0,B:!0,C:!0,D:!0,E:!0,F:!0},counter:0,getColor:function(){var a=Trend[k].Base.colorDefaultVault,b=a.colorArrayLight,c=a.counter;c>=b.length&&(c%=b.length);b=b[c];a.counter++;
return"#"+b},testColor:function(a){var b=!1,c=Trend[k].Base.colorDefaultVault.validationObj;if("undefined"!==typeof a){a=a.replace("#","");if(6<a.length)return b;for(var e=0;e<a.length;e++)if("undefined"!==typeof c[a.charAt(e)])b=c[a.charAt(e)];else{b=!1;break}}return b}},legendSize:{x:0,y:0,w:0,h:0},trendsPlace:{x:0,y:0,w:0,h:0},symbols:[{symbol:/&#34;/g,replacement:'"'},{symbol:/&quot;/g,replacement:'"'},{symbol:/&ldquo;/g,replacement:"\u201c"},{symbol:/&#8220;/g,replacement:"\u201c"},{symbol:/&rdquo;/g,
replacement:"\u201d"},{symbol:/&#8221;/g,replacement:"\u201d"},{symbol:/&#39;/g,replacement:"'"},{symbol:/&#8216;/g,replacement:"\u2018"},{symbol:/&#8217;/g,replacement:"\u2019"}],changeColor:function(a,b){returnedObject={hexCode:null,rgb:null};var c=a.substring(0,2),e=a.substring(2,4),f=a.substring(4,6),c=parseInt(c,16)+b,e=parseInt(e,16)+b,f=parseInt(f,16)+b;255<c&&(c=255);255<e&&(e=255);255<f&&(f=255);0>c&&(c=0);0>e&&(e=0);0>f&&(f=0);returnedObject.rgb="rgb( "+c+","+f+","+e+" )";c=c.toString(16);
e=e.toString(16);f=f.toString(16);1==c.length&&(c="0"+c);1==e.length&&(e="0"+e);1==f.length&&(f="0"+f);returnedObject.hexCode=c+e+f;return returnedObject},encodeString:function(a){for(var b=Trend[k].Base.symbols,c=b.length;c--;)a=a.replace(b[c].symbol,b[c].replacement);return a},drawLogo:function(){var a=Trend[k];a.NodeFactory[a.Render.render].drawLogo.init()},initBaseParams:function(){var a=Trend[k];a.Base.drawLegend();a.Base.initTrendsPlace()},drawLegendBackground:function(){var a=Trend[k];a.NodeFactory[a.Render.render].drawLegendBackground({x:a.Base.legendSize.x-
a.Base.legendSidePadding,y:a.Base.legendSize.y,w:a.Base.legendSize.w+2*a.Base.legendSidePadding,h:a.Base.legendSize.h})},appendDocumentRef:function(){var a=Trend[k];null!==a.NodeStore.documentFragmentRef&&a.chartContainer.appendChild(a.NodeStore.documentFragmentRef)},drawCaption:function(){var a=Trend[k],b=a.params.xmlData.chart;if(""!==b.caption){var c=a.ParamsChecker.getTitleStyles(),e=document.createElement("div"),c=a.Base.defineUndefinedFontStyles(c);e.style.top=b.chartTopMargin+"px";e.style.left=
"0px";e.style.position="absolute";e.style.width="100%";var f=document.createElement("div");f.style.margin="auto";f.style.width="85%";f.style.textAlign="center";f.style.fontFamily=c.font;f.style.fontSize=c.size+"px";f.style.color="#"+c.color;"1"===c.bold&&(f.style.fontWeight="bold");f.appendChild(document.createTextNode(b.caption));e.appendChild(f);a.relativeContainer.appendChild(e);a.Base.titleHeight=a.getSize(e).height}},defineUndefinedFontStyles:function(a){"undefined"===typeof a.bold&&(a.bold=
"0");"undefined"===typeof a.font&&(a.font="Tahoma");"undefined"===typeof a.size&&(a.size="10");"undefined"===typeof a.color&&(a.color="000000");return a},drawLegend:function(){var a=Trend[k],b=a.params.xmlData.chart;if("1"===b.showLegend){for(var c={},b=b.dataset,e=b.length,f=0;f<e;f++)c[b[f].seriesName]=b[f].color;a.Base.createLegendHTML(c)}},createLegendHTML:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=document.createElement("div");e.style.width="100%";e.style.left="0px";e.style.position=
"absolute";e.style.textAlign="center";e.style.padding="0px";e.style.overflow="auto";e.style.overflowX="hidden";b.relativeContainer.appendChild(e);var f=document.createElement("div");f.style.width="100%";f.style.left="0px";f.style.position="relative";e.appendChild(f);try{tHolder=document.createElement('<table cellpadding="0" cellspacing="0" border="0" align="center">')}catch(g){tHolder=document.createElement("table"),tHolder.setAttribute("cellpadding","0"),tHolder.setAttribute("cellspacing","0"),tHolder.setAttribute("border",
"0"),tHolder.setAttribute("align","center")}tHolder.style.verticalAlign="middle";tHolder.style.margin="auto";tHolder.style.border="0px";var h=document.createElement("tbody"),l=document.createElement("tr"),j=document.createElement("td");j.style.border="0px";l.appendChild(j);h.appendChild(l);tHolder.appendChild(h);f.appendChild(tHolder);for(var m in a){var r=document.createElement("div");r.style.cssFloat="left";r.style.styleFloat="left";r.style.overflow="hidden";r.style.position="relative";r.style.padding=
"0 2px";var n;try{n=document.createElement('<table cellpadding="0" cellspacing="0" border="0">')}catch(p){n=document.createElement("table"),n.setAttribute("cellpadding","0"),n.setAttribute("cellspacing","0"),n.setAttribute("border","0")}n.style.fontFamily=c.outCnvBaseFont;n.style.fontSize=c.outCnvBaseFontSize+"px";n.style.color="#"+c.outCnvBaseFontColor;n.style.maxWidth=b.width*b.Base.legendMaxWidthCoef+"px";n.style.margin="0 10px";n.style.border="0px";var h=document.createElement("tbody"),l=document.createElement("tr"),
q;try{q=document.createElement('<td valign="top">')}catch(t){q=document.createElement("td"),q.setAttribute("valign","top")}q.style.border="0px";var u=document.createElement("div");a[m]=a[m].replace("#","");u.style.position="relative";u.style.width="6px";u.style.height="6px";u.style.margin=parseInt(parseInt(c.outCnvBaseFontSize,10)/2,10)+"px 3px";u.style.border="1px solid #"+a[m];u.style.background="#"+a[m];u.style.verticalAlign="middle";q.appendChild(u);l.appendChild(q);q=document.createElement("td");
q.style.fontSize=c.outCnvBaseFontSize+"px";q.style.color="#"+c.outCnvBaseFontColor;q.style.verticalAlign="middle";q.style.border="0px";""==m?q.innerHTML="&nbsp;":q.appendChild(document.createTextNode(b.Base.encodeString(m)));l.appendChild(q);h.appendChild(l);n.appendChild(h);r.appendChild(n);j.appendChild(r);if(b.getSize(j).width>b.width*b.Base.legendMaxWidthCoef){j.removeChild(r);try{tHolder=document.createElement('<table cellpadding="0" cellspacing="0" border="0" align="center">')}catch(s){tHolder=
document.createElement("table"),tHolder.setAttribute("cellpadding","0"),tHolder.setAttribute("cellspacing","0"),tHolder.setAttribute("border","0"),tHolder.setAttribute("align","center")}tHolder.style.verticalAlign="middle";tHolder.style.margin="auto";tHolder.style.border="0px";h=document.createElement("tbody");l=document.createElement("tr");j=document.createElement("td");l.appendChild(j);h.appendChild(l);tHolder.appendChild(h);f.appendChild(tHolder);j.appendChild(r)}}a=b.getSize(e);m=parseInt(b.Base.legendMaxHeightCoef*
b.height,10);a.height>m&&(a.height=m-parseInt(c.chartBottomMargin,10),e.style.height=a.height+"px");e.style.top=b.height-a.height-parseInt(c.chartBottomMargin,10)-c.legendPadding+"px";e=f.childNodes;m=f=0;for(j=e.length;m<j;m++)r=b.getSize(e[m]).width,r>f&&(f=r);b.Base.legendSize.h=a.height;b.Base.legendSize.w=f;b.Base.legendSize.x=(b.width-f)/2;b.Base.legendSize.y=b.height-a.height-parseInt(c.chartBottomMargin,10)-c.legendPadding},getAllHorizontalLabels:function(){for(var a=[],b=Trend[k].params.xmlData.chart.categories.category,
c=b.length;c--;)a.push(b[c].label);return a},getAllVerticalLabels:function(){for(var a=Trend[k].params.xmlData.chart,b=[],c=a.trendLines.line,e=c.length;e--;)b.push(c[e].displayvalue);c=parseInt(a.numdivlines,10)+1;c=(parseFloat(a.yAxisMaxValue,10)-parseFloat(a.yAxisMinValue,10))/c;for(e=a.yAxisMinValue;e<=a.yAxisMaxValue;e+=c)b.push(a.numberPrefix+e.toFixed(a.decimals)+a.numberSuffix);return b},initTrendsPlace:function(){var a=Trend[k],b=a.params.xmlData.chart,c=0,e=0,f=a.Base.getBiggestVTextSize();
a.Base.leftLabelsWidth=f.w;var f=a.Base.leftLabelsWidth,g=a.Base.getBiggestHTextSize();a.Base.bottomLabelsHeight=g.h+2*a.Base.bottomLabelsPadding;""!==b.caption&&(c=a.Base.titleHeight+a.Base.titleBottomSpacing);"0"!==b.showLegend&&(e=a.Base.legendSize.h);"1"===b.rotateNames&&(a.Base.bottomLabelsHeight=g.w+2*a.Base.bottomLabelsPadding);a.Base.trendsPlace.x=f+parseInt(b.chartLeftMargin,10);a.Base.trendsPlace.y=c+parseInt(b.chartTopMargin,10);a.Base.trendsPlace.w=a.width-a.Base.trendsPlace.x-parseInt(b.chartRightMargin,
10);a.Base.trendsPlace.h=a.height-a.Base.trendsPlace.y-e-a.Base.bottomLabelsHeight-parseInt(b.chartBottomMargin,10)-2*b.legendPadding},drawTrendZones:function(){var a=Trend[k];if(a.ParamsChecker.trendLinesDefined)for(var b=a.NodeFactory[a.Render.render],c=a.params.xmlData.chart.trendLines.line,e=c.length,f=0;f<e;f++)if("undefined"!==typeof c[f].startValue&&"undefined"!==typeof c[f].endValue&&"undefined"!==typeof c[f].isTrendZone&&"undefined"!==typeof c[f].color){if("1"==c[f].isTrendZone){var g=a.Base.getPositionByValue({x:0,
y:c[f].startValue}).y,h=a.Base.getPositionByValue({x:0,y:c[f].endValue}).y,l="100";"undefined"!==typeof c[f].alpha&&(l=c[f].alpha);b.drawHorizontalSection(g,h,c[f].color,l);"undefined"!==typeof c[f].displayvalue&&b.drawHorizontalLineLabel((h+g)/2,c[f].displayvalue,c[f].color)}}else"undefined"!==typeof c[f].startValue&&"undefined"!==typeof c[f].color&&("undefined"===typeof c[f].isTrendZone&&(c[f].isTrendZone="0"),"0"===c[f].isTrendZone&&(g=1,h=!1,"undefined"!==typeof c[f].thickness&&(g=c[f].thickness),
"undefined"!==typeof c[f].dashed&&"1"==c[f].dashed&&(h=!0),b.drawHorizontalDivLine(a.Base.getPositionByValue({x:0,y:c[f].startValue}).y,c[f].color,g,h),"undefined"!==typeof c[f].displayvalue&&b.drawHorizontalLineLabel(a.Base.getPositionByValue({x:0,y:c[f].startValue}).y,c[f].displayvalue,c[f].color)))},createBackground:function(){var a=Trend[k];a.NodeFactory[a.Render.render].createBackground()},drawChartsPlace:function(){var a=Trend[k],b=a.params.xmlData.chart,c=a.NodeFactory[a.Render.render],e=b.categories.category,
f=e.length,g=parseInt(b.numdivlines,10)+1,h=b.yAxisMinValue,l=b.yAxisMaxValue,g=(b.yAxisMaxValue-h)/g;c.drawChartCanvas();for(var j=0;j<f;j++)"undefined"===typeof e[j].showVerticalLine&&(e[j].showVerticalLine="1"),"1"===e[j].showVerticalLine&&c.drawVerticalDivLine(a.Base.getPositionByValue({x:e[j].x,y:0}).x,e[j].label);if("1"===b.showAlternateHGridColor){j=h;for(e=0;j<l;j+=g)e%2&&(f=Math.max(a.Base.trendsPlace.y,a.Base.getPositionByValue({x:0,y:j+g}).y),c.drawHorizontalSection(a.Base.getPositionByValue({x:0,
y:j}).y,f,b.AlternateHGridColor,b.AlternateHGridAlpha)),e++}if("1"!==b.showAlternateHGridColor)for(j=h;j<l;j+=g)c.drawHorizontalDivLine(a.Base.getPositionByValue({x:0,y:j}).y,b.divlinecolor,1,!1);for(j=h;parseInt(j,10)<=l;j+=g)h=b.numberPrefix+j.toFixed(b.decimals)+b.numberSuffix,c.drawHorizontalLineLabel(a.Base.getPositionByValue({x:0,y:j}).y,h,b.outCnvBaseFontColor)},drawTrendLines:function(){for(var a=Trend[k],b=a.params.xmlData.chart,c=a.NodeFactory[a.Render.render],e=b.dataset,f=e.length,g=[],
h=b.categories.category,l=h.length,j=0;j<f;j++){var m={color:"",lineThickness:null,categoriesPoints:[],showShadow:null,drawLine:!0,showValues:!1,value:0},n=e[j].set,s=n.length;m.color=e[j].color;m.lineThickness=e[j].lineThickness;m.showShadow=e[j].showShadow;"1"===e[j].drawLine&&(m.drawLine=e[j].drawLine);"1"===e[j].showValues&&(m.showValues=e[j].showValues);for(var p=0;p<l;p++)for(var q=h[p].x,t=0;t<s;t++)if(q===n[t].x){""!==n[t].y?(q=a.Base.getPositionByValue({x:q,y:n[t].y}),m.categoriesPoints.push({x:q.x,
y:q.y,toolText:n[t].toolText,value:n[t].y,url:n[t].url})):m.categoriesPoints.push(null);break}g.push(m)}j=0;for(len=g.length;j<len;j++){p=1;for(a=g[j].categoriesPoints.length;p<a;p++)null!==g[j].categoriesPoints[p]&&null!==g[j].categoriesPoints[p-1]&&!isNaN(g[j].categoriesPoints[p-1].y)&&!isNaN(g[j].categoriesPoints[p].y)&&c.drawLine({fromX:g[j].categoriesPoints[p-1].x,fromY:g[j].categoriesPoints[p-1].y,toX:g[j].categoriesPoints[p].x,toY:g[j].categoriesPoints[p].y,color:g[j].color,lineThickness:g[j].lineThickness,
showShadow:g[j].showShadow})}if("1"===b.showAnchors){j=0;for(len=g.length;j<len;j++){p=0;for(a=g[j].categoriesPoints.length;p<a;p++)null!==g[j].categoriesPoints[p]&&(isNaN(g[j].categoriesPoints[p].y)||c.drawAnchor({x:g[j].categoriesPoints[p].x,y:g[j].categoriesPoints[p].y,color:g[j].color,toolText:g[j].categoriesPoints[p].toolText,showValues:g[j].showValues,value:g[j].categoriesPoints[p].value,url:g[j].categoriesPoints[p].url}))}}},getBiggestVTextSize:function(){var a=Trend[k],b=a.params.xmlData.chart,
c=a.NodeFactory[a.Render.render],a=a.Base.getAllVerticalLabels();return c.getBiggestBBox(a,{fontFamily:b.outCnvBaseFont,fontSize:b.outCnvBaseFontSize})},getBiggestHTextSize:function(){var a=Trend[k],b=a.NodeFactory[a.Render.render],a=a.Base.getAllHorizontalLabels(),c=b.addStylesToCategoriesLabel();return b.getBiggestBBox(a,c)},getPositionByValue:function(a){var b=Trend[k],c=b.params.xmlData.chart,c=b.params.xmlData.chart,e=c.categories.category,f=0,g={x:0,y:0},h=e.length;a.x=parseFloat(a.x,10);a.y=
parseFloat(a.y,10);for(var l=0;l<h;l++)if(parseFloat(e[l].x,10)==a.x){f=l;break}1===h&&(h=3,f=1);g.x=b.Base.trendsPlace.x+b.Base.trendsPlace.w/(h-1)*f;e=b.Base.trendsPlace.h;g.y=e-(a.y-c.yAxisMinValue)/(c.yAxisMaxValue-c.yAxisMinValue)*e+b.Base.trendsPlace.y;return g}},ToolTip:{reference:null,visible:!1,initialize:function(){var a=Trend[k],b=a.params.xmlData.chart,c=document.getElementById("Trend-chart-"+k+"-tooltip-container");c||(c=document.createElement("div"),c.id="Trend-chart-"+k+"-tooltip-container");
c.style.position="absolute";c.style.top="0px";c.style.left="0px";c.style.border=b.toolTipBorderWidth+"px solid #"+b.toolTipBorderColor;c.style.display="none";c.style.padding="3px 5px";c.style.background="#"+b.toolTipBgColor;c.style.fontFamily=b.toolTipFontFamily;c.style.fontSize=b.toolTipFontSize+"px";c.style.color="#"+b.toolTipFontColor;c.style.boxShadow="2px 2px 3px #999999";c.style.zIndex="99999";document.getElementsByTagName("body")[0].appendChild(c);a.ToolTip.reference=c;a.addEvent(document,
"mousemove",a.ToolTip.moveHandler)},moveHandler:function(a){if("undefined"!==typeof Trend[k]){var b=Trend[k];b.ToolTip.visible&&(a=a||window.event,b.ToolTip.moveToolTip(a))}},moveToolTip:function(a){if("undefined"!==typeof a){var b=Trend[k],c=0,e=0;a.pageX||a.pageY?(c=a.pageX,e=a.pageY):(c=a.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft)-document.documentElement.clientLeft,e=a.clientY+(document.documentElement.scrollTop||document.body.scrollTop)-document.documentElement.clientTop);
b.ToolTip.reference.style.left=c+20+"px";b.ToolTip.reference.style.top=e+20+"px"}},show:function(a){var b=Trend[k];b.ToolTip.moveToolTip(window.event);b.deleteChilds(b.ToolTip.reference);null!==b.ToolTip&&(b.ToolTip.reference.innerHTML=a,b.ToolTip.reference.style.display="block",b.ToolTip.visible=!0)},hide:function(){var a=Trend[k];null!==a.ToolTip&&(a.ToolTip.visible=!1,a.ToolTip.reference.style.display="none")}},ParamsChecker:{stylesDefined:!1,trendLinesDefined:!1,getSizeFromParams:function(a,b,
c){var e=!1,f=!1,g=0,h=0;c=Trend[k].getSize(c);var l=typeof a,j=typeof b;"undefined"!==l&&(e=!0,g="string"===l?null!==a.match("%")?parseInt(c.width*parseFloat(a,10)/100,10):isNaN(parseInt(a,10))?c.width:parseInt(a,10):"number"===l?parseInt(a,10):c.width);"undefined"!==j&&(f=!0,h="string"===j?null!==b.match("%")?parseInt(c.height*parseFloat(b,10)/100,10):isNaN(parseInt(b,10))?c.height:parseInt(b,10):"number"===j?parseInt(b,10):c.height);e||(g=c.width);f||(h=c.height);return{width:g,height:h}},checkParams:function(){var a=
Trend[k];a.ParamsChecker.getMinMax();a.ParamsChecker.checkStyles();a.ParamsChecker.defineCaption();a.ParamsChecker.defineLegend();a.ParamsChecker.defineChartMargins();a.ParamsChecker.defineFonts();a.ParamsChecker.defineChartCanvas();a.ParamsChecker.defineNamesRotation();a.ParamsChecker.defineDivLines();a.ParamsChecker.defineAlternateHGrid();a.ParamsChecker.defineLineParams();a.ParamsChecker.defineAnchor();a.ParamsChecker.defineTrendZones();a.ParamsChecker.defineSuffixPreffix();a.ParamsChecker.defineDecimals();
a.ParamsChecker.defineBackground();a.ParamsChecker.defineCategories();a.ParamsChecker.defineTooltip();a.ParamsChecker.defineLineHoverColor();a.ParamsChecker.defineDatasets();return!0},defineDatasets:function(){var a=Trend[k],b=a.params.xmlData.chart,c=b.dataset;"undefined"===typeof b.categories.category.length&&(b.categories.category=[b.categories.category]);"undefined"===typeof c.length&&(c=[c]);for(b=c.length;b--;)if("undefined"===typeof c[b].lineThickness&&(c[b].lineThickness="5"),"undefined"===
typeof c[b].showShadow&&(c[b].showShadow="0"),"undefined"===typeof c[b].drawLine&&(c[b].drawLine="1"),"undefined"===typeof c[b].showValues&&(c[b].showValues="1"),"undefined"===typeof c[b].seriesName&&(c[b].seriesName=""),c[b].color="undefined"===typeof c[b].color||!a.Base.colorDefaultVault.testColor(c[b].color)?a.Base.colorDefaultVault.getColor().replace("#",""):c[b].color.replace("#",""),"undefined"!==typeof c[b].set)for(var e=c[b].set.length;e--;){"undefined"===typeof c[b].set[e].url&&(c[b].set[e].url=
"");"undefined"===typeof c[b].set[e].value&&(c[b].set[e].value="0");if("undefined"!==typeof c[b].set[e].color||!a.Base.colorDefaultVault.testColor(c[b].set[e].color))c[b].set[e].color=a.Base.colorDefaultVault.getColor();"undefined"===typeof c[b].set[e].toolText&&(c[b].set[e].toolText="")}},getMinMax:function(){var a=Trend[k],b=a.params.xmlData.chart,c=999999,e=-999999,f=999999,g=-999999;"undefined"!==typeof b.xAxisMinValue&&(c=parseFloat(b.xAxisMinValue,10));"undefined"!==typeof b.xAxisMaxValue&&
(e=parseFloat(b.xAxisMaxValue,10));"undefined"!==typeof b.yAxisMinValue&&(f=parseFloat(b.yAxisMinValue,10));"undefined"!==typeof b.yAxisMaxValue&&(g=parseFloat(b.yAxisMaxValue,10));"undefined"===typeof b.categories.category.length&&(b.categories.category=[b.categories.category]);"undefined"===typeof b.dataset.length&&(b.dataset=[b.dataset]);for(var h=b.categories.category,l=h.length;l--;)e<parseFloat(h[l].x,10)&&(e=parseFloat(h[l].x,10)),c>parseFloat(h[l].x,10)&&(c=parseFloat(h[l].x,10));h=b.dataset;
for(l=h.length;l--;){if("undefined"!==typeof h[l].set){"undefined"===typeof h[l].set.length&&(h[l].set=[h[l].set]);for(var j=h[l].set.length;j--;){var m=parseFloat(h[l].set[j].y,10);g<m&&(g=m);f>m&&(f=m)}}if("undefined"===typeof h[l].color||!a.Base.colorDefaultVault.testColor(h[l].color))h[l].color=a.Base.colorDefaultVault.getColor()}b.yAxisMinValue=f;b.yAxisMaxValue=g;b.xAxisMinValue=c;b.xAxisMaxValue=e},defineCategories:function(){var a=Trend[k],b=a.params.xmlData.chart,c=b.xAxisMaxValue,e=b.xAxisMinValue,
f=!1,g=!1;"undefined"===typeof b.categories.category.length&&(b.categories.category=[b.categories.category]);for(var h=b.categories.category,l=0,j=h.length;l<j;l++)"undefined"!==typeof h[l].label&&(h[l].label=a.Base.encodeString(h[l].label)),parseFloat(h[l].x,10)===c&&(f=!0),parseFloat(h[l].x,10)===e&&(g=!0);if(!g){a=[];a.push({label:"",showVerticalLine:"1",x:e});l=0;for(j=h.length;l<j;l++)a.push(h[l]);b.categories.category=a}f||b.categories.category.push({label:"",showVerticalLine:"1",x:c})},defineDecimals:function(){var a=
Trend[k].params.xmlData.chart;a.decimals="undefined"===typeof a.decimals?0:parseInt(a.decimals,10)},defineLegend:function(){var a=Trend[k],b=a.params.xmlData.chart;"undefined"===typeof b.showLegend&&(b.showLegend="1");b.legendPadding="undefined"===typeof b.legendPadding?5:parseInt(b.legendPadding,10);b.legendBgColor="undefined"===typeof b.legendBgColor||!a.Base.colorDefaultVault.testColor(b.legendBgColor)?"f0f3ed":b.legendBgColor.replace("#","");if("undefined"===typeof b.legendBorderColor||!a.Base.colorDefaultVault.testColor(b.legendBorderColor))b.legendBorderColor=
"DADADA";"undefined"===typeof b.legendBorderWidth&&(b.legendBorderWidth="1")},defineTooltip:function(){var a=Trend[k],b=a.params.xmlData.chart;b.toolTipBgColor="undefined"===typeof b.toolTipBgColor||!a.Base.colorDefaultVault.testColor(b.toolTipBgColor)?"eaeaea":b.toolTipBgColor.replace("#","");b.toolTipBorderColor="undefined"===typeof b.toolTipBorderColor||!a.Base.colorDefaultVault.testColor(b.toolTipBorderColor)?"7e7e7e":b.toolTipBorderColor.replace("#","");"undefined"===typeof b.toolTipBorderWidth&&
(b.toolTipBorderWidth="1");"undefined"===typeof b.toolTipFontFamily&&(b.toolTipFontFamily="Tahoma, Arial");"undefined"===typeof b.toolTipFontSize&&(b.toolTipFontSize="10");if("undefined"===typeof b.toolTipFontColor||!a.Base.colorDefaultVault.testColor(b.toolTipFontColor))b.toolTipFontColor="333333"},defineTrendZones:function(){var a=Trend[k],b=a.params.xmlData.chart;if("undefined"!==typeof b.trendLines)if(null!==b.trendLines){if("undefined"!==typeof b.trendLines.line&&null!==b.trendLines.line){"undefined"===
typeof b.trendLines.line.length&&(b.trendLines.line=[b.trendLines.line]);for(var c=b.trendLines.line.length;c--;)"undefined"!==typeof b.trendLines.line[c].displayvalue&&(b.trendLines.line[c].displayvalue=a.Base.encodeString(b.trendLines.line[c].displayvalue));a.ParamsChecker.trendLinesDefined=!0}}else b.trendLines={},b.trendLines.line=[];else b.trendLines={},b.trendLines.line=[]},defineAnchor:function(){var a=Trend[k],b=a.params.xmlData.chart;"undefined"===typeof b.showAnchors&&(b.showAnchors="1");
"undefined"===typeof b.anchorRadius&&(b.anchorRadius="3");"undefined"===typeof b.anchorAlpha&&(b.anchorAlpha="100");"undefined"===typeof b.anchorBorderThickness&&(b.anchorBorderThickness="1");b.anchorBgColor="undefined"===typeof b.anchorBgColor||!a.Base.colorDefaultVault.testColor(b.anchorBgColor)?"ffffff":b.anchorBgColor.replace("#","")},defineLineParams:function(){var a=Trend[k].params.xmlData.chart;"undefined"===typeof a.lineAlpha&&(a.lineAlpha="80");"undefined"===typeof a.lineThickness&&(a.lineThickness=
"2")},defineLineHoverColor:function(){var a=Trend[k],b=Trend[k].params.xmlData.chart;if("undefined"===typeof b.lineHoverColor||!a.Base.colorDefaultVault.testColor(b.lineHoverColor))b.lineHoverColor="none"},defineFonts:function(){var a=Trend[k],b=a.params.xmlData.chart;"undefined"===typeof b.baseFont&&(b.baseFont="Tahoma");b.baseFontColor="undefined"===typeof b.baseFontColor||!a.Base.colorDefaultVault.testColor(b.baseFontColor)?"000000":b.baseFontColor.replace("#","");"undefined"===typeof b.baseFontSize&&
(b.baseFontSize="10");"undefined"===typeof b.outCnvBaseFont&&(b.outCnvBaseFont="Tahoma");b.outCnvBaseFontColor="undefined"===typeof b.outCnvBaseFontColor||!a.Base.colorDefaultVault.testColor(b.outCnvBaseFontColor)?"000000":b.outCnvBaseFontColor.replace("#","");"undefined"===typeof b.outCnvBaseFontSize&&(b.outCnvBaseFontSize="10")},defineChartMargins:function(){var a=Trend[k].params.xmlData.chart;"undefined"===typeof a.chartLeftMargin&&(a.chartLeftMargin="4");"undefined"===typeof a.chartRightMargin&&
(a.chartRightMargin="4");"undefined"===typeof a.chartTopMargin&&(a.chartTopMargin="4");"undefined"===typeof a.chartBottomMargin&&(a.chartBottomMargin="4")},defineAlternateHGrid:function(){var a=Trend[k],b=a.params.xmlData.chart;"undefined"===typeof b.showAlternateHGridColor&&(b.showAlternateHGridColor="1");b.AlternateHGridColor="undefined"===typeof b.AlternateHGridColor||!a.Base.colorDefaultVault.testColor(b.AlternateHGridColor)?"CCCCCC":b.AlternateHGridColor.replace("#","");"undefined"===typeof b.AlternateHGridAlpha&&
(b.AlternateHGridAlpha="30")},defineNamesRotation:function(){var a=Trend[k].params.xmlData.chart;"undefined"===typeof a.rotateNames&&(a.rotateNames="0")},defineDivLines:function(){var a=Trend[k],b=a.params.xmlData.chart;b.divlinecolor="undefined"===typeof b.divlinecolor||!a.Base.colorDefaultVault.testColor(b.divlinecolor)?"dadada":b.divlinecolor.replace("#","");"undefined"===typeof b.numdivlines&&(b.numdivlines="3")},defineCaption:function(){var a=Trend[k],b=a.params.xmlData.chart;b.caption="undefined"===
typeof b.caption?"":a.Base.encodeString(b.caption)},defineChartCanvas:function(){var a=Trend[k],b=a.params.xmlData.chart;"undefined"===typeof b.canvasBorderThickness&&(b.canvasBorderThickness="1");b.canvasBorderColor="undefined"===typeof b.canvasBorderColor||!a.Base.colorDefaultVault.testColor(b.canvasBorderColor)?"999999":b.canvasBorderColor.replace("#","");if("undefined"===typeof b.canvasBgColor)b.canvasBgColor="e6e6e6,ffffff";else if(colors=b.canvasBgColor.split(" ").join("").split(","),1===colors.length&&
a.Base.colorDefaultVault.testColor(colors[0]))b.canvasBgColor=b.canvasBgColor.split(" ").join("");else if(1<colors.length){for(var c=!0,e=0,f=colors.length;e<f&&!(c=a.Base.colorDefaultVault.testColor(colors[e]),!c);e++);b.canvasBgColor=c?colors.join(","):"e6e6e6,FFFFFF"}b.canvasBgAngle="undefined"===typeof b.canvasBgAngle?45:parseInt(b.canvasBgAngle,10)%360;b.canvasBgAlpha="undefined"===typeof b.canvasBgAlpha?100:parseInt(b.canvasBgAlpha,10)},checkStyles:function(){var a=Trend[k],b=a.params.xmlData.chart,
c=!1,e=!1,f=!1;"undefined"!==typeof b.styles&&("undefined"!==typeof b.styles.application&&"undefined"!==typeof b.styles.application.apply&&("undefined"===typeof b.styles.application.apply.length&&(b.styles.application.apply=[b.styles.application.apply]),e=!0),"undefined"!==typeof b.styles.definition&&"undefined"!==typeof b.styles.definition.style&&("undefined"===typeof b.styles.definition.style.length&&(b.styles.definition.style=[b.styles.definition.style]),f=!0));f&&e&&(c=!0);a.ParamsChecker.stylesDefined=
c},defineSuffixPreffix:function(){var a=Trend[k].params.xmlData.chart;"undefined"===typeof a.numberSuffix&&(a.numberSuffix="");"undefined"===typeof a.numberPrefix&&(a.numberPrefix="")},defineBackground:function(){var a=Trend[k],b=a.params.xmlData.chart;if("undefined"===typeof b.bgColor)b.bgColor="bbbbbb,FFFFFF";else if(colors=b.bgColor.split(" ").join("").split(","),1===colors.length&&a.Base.colorDefaultVault.testColor(colors[0]))b.bgColor=b.bgColor.split(" ").join("");else if(1<colors.length){for(var c=
!0,e=0,f=colors.length;e<f&&!(c=a.Base.colorDefaultVault.testColor(colors[e]),!c);e++);b.bgColor=c?colors.join(","):"bbbbbb,FFFFFF"}b.bgAngle="undefined"===typeof b.bgAngle?45:parseInt(b.bgAngle,10)%360;b.bgAlpha="undefined"===typeof b.bgAlpha?100:parseInt(b.bgAlpha,10)},getTitleStyles:function(){var a=Trend[k],b=a.params.xmlData.chart,c={};if(a.ParamsChecker.stylesDefined){for(var e=b.styles.application.apply,f="",g=0,h=e.length;g<h;g++)"Caption"===e[g].toObject&&(f=e[g].styles);if(""!==f){b=b.styles.definition.style;
g=0;for(h=b.length;g<h;g++)b[g].name==f&&"font"==b[g].type&&(c.bold="undefined"!==typeof b[g].bold?b[g].bold:"0",c.font="undefined"!==typeof b[g].font?b[g].font:"Tahoma",c.color="undefined"!==typeof b[g].color&&a.Base.colorDefaultVault.testColor(b[g].color)?b[g].color:"000000",c.size="undefined"!==typeof b[g].size?b[g].size:"10")}}return c}},createChartContainers:function(a){var b=Trend[k],c=document.createElement("div");c.style.width=b.width+"px";c.style.height=b.height+"px";c.style.position="relative";
c.style.padding="0";c.style.margin="0";c.style.top="0px";c.style.left="0px";a.appendChild(c);d=document.createElement("div");d.style.width=b.width+"px";d.style.height=b.height+"px";d.style.position="absolute";d.style.padding="0";d.style.margin="0";d.style.top="0px";d.style.left="0px";c.appendChild(d);return{chartContainer:d,relativeContainer:c}},getSize:function(a){var b=0,c=0,e=0,f=0,g=0,h=0;Trend[k].Render.isMobile.any()&&("undefined"!==typeof a.scrollWidth&&(b=a.scrollWidth),"undefined"!==typeof a.scrollHeight&&
(c=a.scrollHeight));"undefined"!==typeof a.offsetWidth&&(e=a.offsetWidth);"undefined"!==typeof a.offsetHeight&&(f=a.offsetHeight);"undefined"!==typeof a.clientWidth&&(g=a.clientWidth);"undefined"!==typeof a.clientHeight&&(h=a.clientHeight);return{width:Math.max(g,e,b),height:Math.max(h,f,c)}},deleteChilds:function(a){for(var b=a.childNodes,c=b.length;c--;)a.removeChild(b[c])},addEvent:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c},
Render:{svgNS:"http://www.w3.org/2000/svg",render:null,androidDetected:!1,isMobile:{Android:function(){return navigator.userAgent.match(/Android/i)?!0:!1},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)?!0:!1},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)?!0:!1},Windows:function(){return navigator.userAgent.match(/IEMobile/i)?!0:!1},any:function(){var a=Trend[k].Render;return a.isMobile.Android()||a.isMobile.BlackBerry()||a.isMobile.iOS()||a.isMobile.Windows()}},
detectAndroid:function(){var a=navigator.userAgent.toLowerCase();Trend[k].Render.androidDetected=-1<a.indexOf("android")},supportsSVG:function(){return!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},supportsVML:function(){var a=document.body.appendChild(document.createElement("div"));a.innerHTML='<v:shape id="vml_flag1" adj="1" />';var b=a.firstChild;b.style.behavior="url(#default#VML)";b=b?"object"==typeof b.adj:!0;a.parentNode.removeChild(a);
return b},supportsCanvas:function(){var a=document.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))},InitializeRender:function(){var a=Trend[k];a.Render.detectAndroid();var b=a.Render.supportsSVG(),c=a.Render.supportsVML(),e=a.Render.supportsCanvas();if(b)a.Render.render="SVG";else if(c)a.Render.render="VML";else if(e)a.Render.render="Canvas";else throw Error("Not Found any supported renderer for Trend chart!");}},NodeStore:{root:null,documentFragmentRef:null},NodeFactory:{SVG:{legendShadowID:null,
createRoot:function(){var a=Trend[k],b=document.createDocumentFragment(),c=document.createElementNS(a.Render.svgNS,"svg");b.appendChild(c);c.setAttribute("width",a.width);c.setAttribute("height",a.height);a.NodeStore.documentFragmentRef=b;a.NodeStore.root=c;a.NodeFactory.SVG.createLegendShadow()},drawLogo:{init:function(){var a=Trend[k],b=a.NodeStore.root,c=a.width-130,e=a.height-50;parseInt(1073741824*Math.random(),10);a.NodeFactory.SVG.drawLogo.drawCirclePart({angleStart:70,angleEnd:340,color:"#434343",
cx:c+20,cy:e+20,radius:20,container:b});a.NodeFactory.SVG.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+20+2,cy:e+20+1,radius:20,container:b});a.NodeFactory.SVG.drawLogo.createText(b,c+20+9,e+20+13)},logoHoverHandler:function(a){var b=Trend[k];b.addEvent(a,"mouseover",function(a){a.target.style.cursor="pointer"});b.addEvent(a,"click",function(){window.location.assign("http://www.hdcharts.com/")});b.addEvent(a,"mouseout",function(a){a.target.style.cursor="default"})},drawPoly:function(a){var b=
Trend[k],c=document.createElementNS(b.Render.svgNS,"path"),e,f=a.points,g=f.length-1;for(e="M"+(f[g].x+" "+f[g].y);g--;)e=e+"L"+f[g].x+" "+f[g].y;c.setAttribute("d",e+" z");c.setAttribute("fill",a.color);c.setAttribute("fill-opacity",a.opacity);a.container.appendChild(c);b.NodeFactory.SVG.drawLogo.logoHoverHandler(c)},drawCirclePart:function(a){var b=Trend[k],c=[],e=a.cx,f=a.cy,g=a.radius;c.push({x:e,y:f});for(var h=a.angleStart;h<=a.angleEnd;h++){var l=h*(Math.PI/180),j=0,m=0,j=e+g*Math.cos(l),m=
f+g*Math.sin(l);c.push({x:j,y:m})}b.NodeFactory.SVG.drawLogo.drawPoly({points:c,color:a.color,container:a.container})},createGradient:function(a,b,c){var e=Trend[k],f=document.createElementNS(e.Render.svgNS,"radialGradient");f.id=b;f.setAttribute("gradientUnits","userSpaceOnUse");f.setAttribute("cx",c.cx);f.setAttribute("cy",c.cy);f.setAttribute("r",c.radius);b=document.createElementNS(e.Render.svgNS,"stop");b.setAttribute("offset","0%");b.setAttribute("stop-color","#5f5f5f");b.setAttribute("stop-opacity",
"100");f.appendChild(b);e=document.createElementNS(e.Render.svgNS,"stop");e.setAttribute("offset","100%");e.setAttribute("stop-color","#434343");e.setAttribute("stop-opacity","100");f.appendChild(e);a.appendChild(f)},createText:function(a,b,c){var e=Trend[k],f=document.createElementNS(e.Render.svgNS,"text");f.appendChild(document.createTextNode("HD"));f.style.fontFamily="Tahoma";f.style.fontSize="17px";f.style.fontWeight="bold";f.setAttribute("fill","#434343");f.setAttribute("x",b);f.setAttribute("y",
c);a.appendChild(f);e.NodeFactory.SVG.drawLogo.logoHoverHandler(f);f=document.createElementNS(e.Render.svgNS,"text");f.appendChild(document.createTextNode("CHARTS"));f.style.fontFamily="Tahoma";f.style.fontSize="17px";f.style.fontWeight="bold";f.setAttribute("fill","#F15A23");f.setAttribute("x",b+27);f.setAttribute("y",c);a.appendChild(f);e.NodeFactory.SVG.drawLogo.logoHoverHandler(f)}},initBackgroundGradient:function(a,b,c){var e=Trend[k],f=document.createElementNS(e.Render.svgNS,"linearGradient");
f.id="Trend-background-gradient-"+k+"-"+a+"-"+b+"-"+c;c=parseInt(c);switch(c){case 0:f.setAttribute("x1","0%");f.setAttribute("y1","100%");f.setAttribute("x2","0%");f.setAttribute("y2","0%");break;case 45:f.setAttribute("x1","100%");f.setAttribute("y1","100%");f.setAttribute("x2","0%");f.setAttribute("y2","0%");break;case 90:f.setAttribute("x1","100%");f.setAttribute("y1","0%");f.setAttribute("x2","0%");f.setAttribute("y2","0%");break;case 135:f.setAttribute("x1","100%");f.setAttribute("y1","0%");
f.setAttribute("x2","0%");f.setAttribute("y2","100%");break;case 180:f.setAttribute("x1","0%");f.setAttribute("y1","0%");f.setAttribute("x2","0%");f.setAttribute("y2","100%");break;case 225:f.setAttribute("x1","0%");f.setAttribute("y1","0%");f.setAttribute("x2","100%");f.setAttribute("y2","100%");break;case 270:f.setAttribute("x1","0%");f.setAttribute("y1","0%");f.setAttribute("x2","100%");f.setAttribute("y2","0%");break;case 315:f.setAttribute("x1","0%");f.setAttribute("y1","100%");f.setAttribute("x2",
"100%");f.setAttribute("y2","0%");break;case 360:f.setAttribute("x1","0%"),f.setAttribute("y1","100%"),f.setAttribute("x2","0%"),f.setAttribute("y2","0%")}c=document.createElementNS(e.Render.svgNS,"stop");c.setAttribute("offset","0%");c.setAttribute("stop-color",a);f.appendChild(c);a=document.createElementNS(e.Render.svgNS,"stop");a.setAttribute("offset","100%");a.setAttribute("stop-color",b);f.appendChild(a);e.NodeStore.root.appendChild(f);e.NodeFactory.SVG.backgroundGradient=f;return f.id},createLegendShadow:function(){var a=
Trend[k],b=document.createElementNS(a.Render.svgNS,"filter");a.NodeFactory.SVG.legendShadowID="trend-chart-"+k+"-legend-shadow";b.setAttribute("id",a.NodeFactory.SVG.legendShadowID);b.setAttribute("x","0");b.setAttribute("y","0");b.setAttribute("width","250%");b.setAttribute("height","250%");var c=document.createElementNS(a.Render.svgNS,"feOffset");c.setAttribute("result","offOut");c.setAttribute("in","SourceGraphic");c.setAttribute("dx","2");c.setAttribute("dy","2");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,
"feColorMatrix");c.setAttribute("result","matrixOut");c.setAttribute("in","offOut");c.setAttribute("type","matrix");c.setAttribute("values","0.1 0 0 0 0 0 0.1 0 0 0 0 0 0.1 0 0 0 0 0 0.7 0");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"feGaussianBlur");c.setAttribute("result","blurOut");c.setAttribute("in","matrixOut");c.setAttribute("stdDeviation","2");b.appendChild(c);c=document.createElementNS(a.Render.svgNS,"feBlend");c.setAttribute("in","SourceGraphic");c.setAttribute("in2","blurOut");
c.setAttribute("mode","normal");b.appendChild(c);a.NodeStore.root.appendChild(b)},createBackground:function(){var a=Trend[k],b=a.params.xmlData.chart,c=document.createElementNS(a.Render.svgNS,"rect"),e=b.bgAlpha/100;c.setAttribute("x",0);c.setAttribute("y",0);c.setAttribute("width",a.width);c.setAttribute("height",a.height);c.setAttribute("fill-opacity",e);e=b.bgColor.split(",");1==e.length?c.setAttribute("fill","#"+b.bgColor):(b=a.NodeFactory.SVG.initBackgroundGradient("#"+e[0],"#"+e[1],b.bgAngle),
c.setAttribute("fill","url(#"+b+")"));a.NodeStore.root.appendChild(c)},drawChartCanvas:function(){var a=Trend[k],b=a.params.xmlData.chart,c=document.createElementNS(a.Render.svgNS,"path");c.setAttribute("fill-opacity",b.canvasBgAlpha/100);c.setAttribute("d","M"+a.Base.trendsPlace.x+" "+a.Base.trendsPlace.y+"L"+a.Base.trendsPlace.x+" "+(a.Base.trendsPlace.y+a.Base.trendsPlace.h)+"L"+(a.Base.trendsPlace.x+a.Base.trendsPlace.w)+" "+(a.Base.trendsPlace.y+a.Base.trendsPlace.h)+"L"+(a.Base.trendsPlace.x+
a.Base.trendsPlace.w)+" "+a.Base.trendsPlace.y+"z");var e=b.canvasBgColor.split(",");1==e.length?c.setAttribute("fill","#"+b.canvasBgColor):(e=a.NodeFactory.SVG.initBackgroundGradient("#"+e[0],"#"+e[1],b.canvasBgAngle),c.setAttribute("fill","url(#"+e+")"));c.setAttribute("stroke","#"+b.canvasBorderColor);c.setAttribute("stroke-width",b.canvasBorderThickness);a.NodeStore.root.appendChild(c)},drawVerticalDivLine:function(a,b){var c=Trend[k],e=c.params.xmlData.chart,f=a-c.Base.leftLabelsOffset,g=c.Base.trendsPlace.y+
c.Base.trendsPlace.h,h=document.createElementNS(c.Render.svgNS,"path");h.setAttribute("d","M"+a+" "+c.Base.trendsPlace.y+"L"+a+" "+(c.Base.trendsPlace.y+c.Base.trendsPlace.h));h.setAttribute("stroke","#"+e.divlinecolor);h.setAttribute("stroke-width","1");c.NodeStore.root.appendChild(h);h=document.createElementNS(c.Render.svgNS,"text");h.appendChild(document.createTextNode(b));var l=c.NodeFactory.SVG.addStylesToCategoriesLabel(h);c.NodeStore.root.appendChild(h);c=c.NodeFactory.SVG.getBiggestBBox([b],
l);"0"===e.rotateNames?(h.setAttribute("y",g+c.h),h.setAttribute("x",f-c.w/2)):(h.setAttribute("x",f-c.w/2-4),h.setAttribute("y",g+c.w/2+c.h/2),h.setAttribute("transform","rotate(-90 "+f+","+(g+c.w/2)+")"))},drawHorizontalDivLine:function(a,b,c,e){var f=Trend[k],g=document.createElementNS(f.Render.svgNS,"path");g.setAttribute("d","M"+f.Base.trendsPlace.x+" "+a+"L"+(f.Base.trendsPlace.x+f.Base.trendsPlace.w)+" "+a);g.setAttribute("stroke","#"+b);g.setAttribute("stroke-width",c);e&&g.setAttribute("stroke-dasharray",
"9, 5");f.NodeStore.root.appendChild(g)},drawHorizontalLineLabel:function(a,b,c){var e=Trend[k],f=e.params.xmlData.chart,g=e.Base.trendsPlace.x,h=document.createElementNS(e.Render.svgNS,"text");h.appendChild(document.createTextNode(b));h.setAttribute("x",g);h.setAttribute("y",a);h.style.fontFamily=f.outCnvBaseFont;h.style.fontSize=f.outCnvBaseFontSize+"px";h.setAttribute("fill","#"+c);b=e.NodeFactory.SVG.getBiggestBBox([b],{fontFamily:f.outCnvBaseFont,fontSize:f.outCnvBaseFontSize});e.NodeStore.root.appendChild(h);
h.setAttribute("x",g-b.w-5);h.setAttribute("y",a+b.h/4)},drawHorizontalSection:function(a,b,c,e){var f=Trend[k],g=document.createElementNS(f.Render.svgNS,"path");g.setAttribute("d","M"+f.Base.trendsPlace.x+" "+a+"L"+f.Base.trendsPlace.x+" "+b+"L"+(f.Base.trendsPlace.x+f.Base.trendsPlace.w)+" "+b+"L"+(f.Base.trendsPlace.x+f.Base.trendsPlace.w)+" "+a+"z");g.setAttribute("fill","#"+c);g.setAttribute("stroke-width",0);g.setAttribute("fill-opacity",(parseInt(e,10)/100).toFixed(2));f.NodeStore.root.appendChild(g)},
drawLine:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=document.createElementNS(b.Render.svgNS,"path"),f=null;e.setAttribute("d","M"+a.fromX+" "+a.fromY+"L"+a.toX+" "+a.toY);e.setAttribute("fill","#"+a.color);e.setAttribute("stroke","#"+a.color);e.setAttribute("stroke-opacity",parseInt(c.lineAlpha,10)/100);var g={line:e,color:a.color,alpha:parseInt(c.lineAlpha,10)};(f=null!==a.lineThickness?a.lineThickness:c.lineThickness)&&e.setAttribute("stroke-width",f);null!==a.showShadow&&(c=b.Base.shadowOffset,
a="M"+(a.fromX+c)+" "+(a.fromY+c)+"L"+(a.toX+c)+" "+(a.toY+c),c=document.createElementNS(b.Render.svgNS,"path"),c.setAttribute("d",a),c.setAttribute("fill","#999999"),c.setAttribute("stroke","#999999"),c.setAttribute("stroke-opacity",b.Base.shadowOpacity/100),f&&c.setAttribute("stroke-width",parseInt(parseInt(f,10)*b.Base.shadowWidthCoef,10)),b.NodeStore.root.appendChild(c));b.NodeStore.root.appendChild(e);f=new b.NodeFactory.SVG.anchorHoverHandler(void 0,g,void 0,void 0);g=new b.NodeFactory.SVG.anchorOutHandler(g);
b.addEvent(e,"mouseover",f);b.addEvent(e,"mouseout",g)},anchorHoverHandler:function(a,b,c,e){return function(){if("undefined"!==typeof b){var f=Trend[k].params.xmlData.chart;"default"===f.lineHoverColor?(f=Trend[k].Base.changeColor(b.color.replace("#",""),25).hexCode,b.line.setAttribute("stroke","#"+f)):"none"!==f.lineHoverColor&&b.line.setAttribute("stroke","#"+f.lineHoverColor.replace("#",""))}f=Trend[k];"undefined"!==typeof a&&""!==a&&f.ToolTip.show(a);"undefined"!==typeof c&&c.setAttribute("r",
parseInt(e,10)+3)}},anchorOutHandler:function(a,b,c){return function(){var e=Trend[k],f=e.params.xmlData.chart;"undefined"!==typeof a&&"none"!==f.lineHoverColor&&a.line.setAttribute("stroke","#"+a.color.replace("#",""));e.ToolTip.hide();"undefined"!==typeof b&&b.setAttribute("r",c)}},drawAnchor:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=document.createElementNS(b.Render.svgNS,"circle"),f=parseInt(c.anchorRadius,10);e.setAttribute("cx",a.x);e.setAttribute("cy",a.y);e.setAttribute("r",f);
e.setAttribute("fill","#"+c.anchorBgColor);e.setAttribute("fill-opacity",parseInt(c.anchorAlpha,10)/100);e.setAttribute("stroke","#"+a.color);e.setAttribute("stroke-width",c.anchorBorderThickness);e.setAttribute("stroke-opacity",parseInt(c.anchorAlpha,10)/100);if("1"===a.showValues){var g=document.createElementNS(b.Render.svgNS,"text"),h=b.Base.anchorLabelOffset,l=a.x,j=a.y-h,m=c.numberPrefix+parseFloat(a.value,10).toFixed(c.decimals)+c.numberSuffix;j<b.Base.trendsPlace.y&&(j=a.y+h);g.appendChild(document.createTextNode(m));
g.setAttribute("x",l);g.setAttribute("y",j);g.style.fontFamily=c.baseFont;g.style.fontSize=c.baseFontSize+"px";g.setAttribute("fill","#"+c.baseFontColor);c=b.NodeFactory.SVG.getBiggestBBox([m],{fontFamily:c.baseFont,fontSize:c.baseFontSize});b.NodeStore.root.appendChild(g);g.setAttribute("x",l-c.w/2);g.setAttribute("y",j+c.h/4)}b.NodeStore.root.appendChild(e);g=new b.NodeFactory.SVG.anchorHoverHandler(a.toolText,void 0,e,f);f=new b.NodeFactory.SVG.anchorOutHandler(void 0,e,f);b.addEvent(e,"mouseover",
g);b.addEvent(e,"mouseout",f);""!==a.url&&(e.style.cursor="pointer",b.addEvent(e,"click",function(){window.open(a.url,"_blank")}))},getBiggestBBox:function(a,b){var c=Trend[k],e=a.length,f=document.createElement("div"),g=0,h=0;f.style.top="-100px";f.style.left="-100px";f.style.position="absolute";f.style.fontFamily=b.fontFamily;f.style.fontSize=b.fontSize+"px";for(c.chartContainer.appendChild(f);e--;){c.deleteChilds(f);f.appendChild(document.createTextNode(a[e]));var l=c.getSize(f);g<l.width&&(g=
l.width);h<l.height&&(h=l.height)}c.chartContainer.removeChild(f);return{w:g,h:h}},addStylesToTextObject:function(a,b){a.style.fontFamily=b.font;a.style.fontSize=b.size+"px";"1"==b.bold&&(a.style.fontWeight="bold");a.setAttribute("fill","#"+b.color)},drawLegendBackground:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=document.createElementNS(b.Render.svgNS,"rect");e.setAttribute("fill","#"+c.legendBgColor);e.setAttribute("x",a.x);e.setAttribute("y",a.y);e.setAttribute("width",a.w);e.setAttribute("height",
a.h);e.setAttribute("stroke","#"+c.legendBorderColor);e.setAttribute("stroke-width",c.legendBorderWidth+"px");b.NodeStore.root.appendChild(e)},addStylesToCategoriesLabel:function(a){var b=Trend[k].params.xmlData.chart,c=b.outCnvBaseFont,e=b.outCnvBaseFontSize,f=b.outCnvBaseFontColor;"undefined"!==typeof b.categories.font&&(c=b.categories.font);"undefined"!==typeof b.categories.fontSize&&(e=b.categories.fontSize);"undefined"!==typeof b.categories.fontColor&&(f=b.categories.fontColor);"undefined"!==
typeof a&&(a.style.fontFamily=c,a.style.fontSize=e+"px",a.setAttribute("fill","#"+f));return{fontFamily:c,fontSize:e,fontColor:f}}},VML:{createNode:null,scaleCoeficient:10,getCoefValue:function(a){return parseInt(parseFloat(a,10)*Trend[k].NodeFactory.VML.scaleCoeficient,10)},createRoot:function(){var a=Trend[k];try{document.createStyleSheet().addRule(".rvml","behavior:url(#default#VML) ")}catch(b){}try{document.namespaces.add("rvml","urn:schemas-microsoft-com:vml"),a.NodeFactory.VML.createNode=function(a,
b){var c=document.createElement("<rvml:"+a+' class="rvml" >');"undefined"===typeof b&&(b=!1);if(b){var e=document.createElement('<rvml:stroke class="rvml" >');e.setAttribute("opacity","0%");c.appendChild(e)}return c}}catch(c){a.NodeFactory.VML.createNode=function(a,b){var c=document.createElement("<"+a+' xmlns="urn:schemas-microsoft.com:vml" class="rvml" >');"undefined"===typeof b&&(b=!1);if(b){var e=document.createElement('<rvml:stroke xmlns="urn:schemas-microsoft.com:vml" class="rvml" >');e.setAttribute("opacity",
"0%");c.appendChild(e)}return c}}var e=document.createElement("div");e.style.width=a.width+"px";e.style.height=a.height+"px";a.NodeStore.documentFragmentRef=document.createDocumentFragment();a.NodeStore.documentFragmentRef.appendChild(e);a.NodeStore.root=e},drawLogo:{init:function(){var a=Trend[k],b=a.NodeStore.root,c=a.width-130,e=a.height-50,f=""+parseInt(1073741824*Math.random(),10);a.NodeFactory.VML.drawLogo.createGradient(b,f,{cx:c+0,cy:e+0,radius:30});a.NodeFactory.VML.drawLogo.drawCirclePart({angleStart:70,
angleEnd:340,color:"#434343",cx:c+0,cy:e+0,radius:20,container:b});a.NodeFactory.VML.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+0+2,cy:e+0+1,radius:20,container:b});a.NodeFactory.VML.drawLogo.createText(b,c+0+9,e+0+13)},logoHoverHandler:function(a){var b=Trend[k];b.addEvent(a,"mouseover",function(a){a.toElement.style.cursor="pointer"});b.addEvent(a,"click",function(){window.location.assign("http://www.hdcharts.com/")});b.addEvent(a,"mouseout",function(a){a.toElement.style.cursor=
"default"})},drawPoly:function(a){var b=Trend[k],c=b.NodeFactory.VML.createNode("shape",!0);c.setAttribute("coordsize",b.NodeFactory.VML.getCoefValue(b.width)+" "+b.NodeFactory.VML.getCoefValue(b.height));c.setAttribute("coordorigin","0 0");c.setAttribute("fillcolor",a.color);c.style.position="absolute";c.style.left="0 px";c.style.top="0 px";c.style.width=b.width+"px";c.style.height=b.height+"px";var e,f=a.points,g=f.length-1,h=b.NodeFactory.VML.scaleCoeficient;for(e="M"+(parseInt(f[g].x*h,10)+" "+
parseInt(f[g].y*h,10));g--;)e=e+"L"+parseInt(f[g].x*h,10)+" "+parseInt(f[g].y*h,10);e+=" z";f=b.NodeFactory.VML.createNode("path");f.setAttribute("v",e);c.appendChild(f);a.container.appendChild(c);b.NodeFactory.VML.drawLogo.logoHoverHandler(c)},drawCirclePart:function(a){var b=Trend[k],c=[],e=a.cx,f=a.cy,g=a.radius;c.push({x:e,y:f});for(var h=a.angleStart;h<=a.angleEnd;h++){var l=h*(Math.PI/180),j=0,m=0,j=e+g*Math.cos(l),m=f+g*Math.sin(l);c.push({x:j,y:m})}b.NodeFactory.VML.drawLogo.drawPoly({points:c,
color:a.color,container:a.container})},createGradient:function(){},createText:function(a,b,c){var e=Trend[k],f="",f="m 0,0 l 1,0 e",g=e.NodeFactory.VML.createNode("shape",!0);g.style.position="absolute";g.style.top=c-3+"px";g.style.left=b+15+"px";g.style.zIndex=0;g.style.width="1px";g.style.height="1px";g.setAttribute("filled","t");g.setAttribute("fillcolor","#434343");g.setAttribute("stroked","f");g.setAttribute("path",f);var h=e.NodeFactory.VML.createNode("textpath");h.style.fontFamily="Tahoma";
h.style.fontSize="17px";h.style.fontWeight="bold";h.setAttribute("fill","#434343");h.setAttribute("on","t");h.setAttribute("string","HD");g.appendChild(h);h=e.NodeFactory.VML.createNode("path");h.setAttribute("textpathok","t");g.appendChild(h);a.appendChild(g);e.NodeFactory.VML.drawLogo.logoHoverHandler(g);g=e.NodeFactory.VML.createNode("shape",!0);g.style.position="absolute";g.style.top=c-3+"px";g.style.left=b+63+"px";g.style.zIndex=0;g.style.width="1px";g.style.height="1px";g.setAttribute("filled",
"t");g.setAttribute("fillcolor","#434343");g.setAttribute("stroked","f");g.setAttribute("path",f);h=e.NodeFactory.VML.createNode("textpath");h.style.fontFamily="Tahoma";h.style.fontSize="17px";h.style.fontWeight="bold";h.setAttribute("fill","#F15A23");h.setAttribute("on","t");h.setAttribute("string","CHARTS");g.appendChild(h);h.setAttribute("x",b+27);h.setAttribute("y",c);h=e.NodeFactory.VML.createNode("path");h.setAttribute("textpathok","t");g.appendChild(h);a.appendChild(g);e.NodeFactory.VML.drawLogo.logoHoverHandler(g)}},
createBackground:function(){var a=Trend[k],b=a.params.xmlData.chart,c=a.NodeFactory.VML.createNode("rect",!0);c.style.top="0px";c.style.left="0px";c.style.width=a.width+"px";c.style.height=a.height+"px";c.style.border="0px";c.style.position="absolute";c.style.filter="alpha(opacity="+b.bgAlpha+")";var e=b.bgColor.split(",");if(1==e.length)c.setAttribute("fillcolor","#"+b.bgColor);else{var f=a.NodeFactory.VML.createNode("fill");f.setAttribute("Type","Gradient");f.setAttribute("Angle",b.bgAngle);f.setAttribute("Color",
"#"+e[0]);f.setAttribute("Color2","#"+e[1]);f.setAttribute("Focus","0%");f.setAttribute("method","none");c.appendChild(f)}a.NodeStore.root.appendChild(c)},addLabel:function(a,b,c,e,f){var g=Trend[k],h="",h=e?"m0,0 l0,-1 e":"m0,0 l1,0 e";e=g.NodeFactory.VML.createNode("shape",!0);e.style.position="absolute";e.style.top=c+"px";e.style.left=b+"px";e.style.zIndex=0;e.style.width="1px";e.style.height="1px";e.setAttribute("filled","t");e.setAttribute("fillcolor","#"+f.color);e.setAttribute("stroked","f");
e.setAttribute("path",h);b=g.NodeFactory.VML.createNode("textpath",!0);b.style.fontFamily=f.font;b.style.fontSize=f.size+"px";b.setAttribute("on","t");b.setAttribute("string",a);e.appendChild(b);a=g.NodeFactory.VML.createNode("path",!0);a.setAttribute("textpathok","t");e.appendChild(a);g.NodeStore.root.appendChild(e);return e},drawChartCanvas:function(){var a=Trend[k],b=a.params.xmlData.chart,c=a.NodeFactory.VML.createNode("rect");c.style.top=parseInt(a.Base.trendsPlace.y,10)+"px";c.style.left=parseInt(a.Base.trendsPlace.x+
1,10)+"px";c.style.width=parseInt(a.Base.trendsPlace.w,10)+"px";c.style.height=parseInt(a.Base.trendsPlace.h,10)+"px";c.style.position="absolute";c.setAttribute("stroke","true");c.setAttribute("strokecolor","#"+b.canvasBorderColor);c.setAttribute("strokeweight",b.canvasBorderThickness);c.style.filter="alpha(opacity="+b.canvasBgAlpha+")";var e=b.canvasBgColor.split(",");if(1==e.length)c.setAttribute("fillcolor","#"+b.canvasBgColor);else{var f=a.NodeFactory.VML.createNode("fill");f.setAttribute("Type",
"Gradient");f.setAttribute("Angle",b.canvasBgAngle);f.setAttribute("Color","#"+e[0]);f.setAttribute("Color2","#"+e[1]);f.setAttribute("Focus","0%");f.setAttribute("method","none");c.appendChild(f)}a.NodeStore.root.appendChild(c)},drawVerticalDivLine:function(a,b){var c=Trend[k],e=c.params.xmlData.chart,f=parseInt(a-c.Base.leftLabelsOffset,10),g=parseInt(c.Base.trendsPlace.y+c.Base.trendsPlace.h,10),h=c.NodeFactory.VML.createNode("line");h.setAttribute("from",parseInt(a,10)+","+parseInt(c.Base.trendsPlace.y,
10));h.setAttribute("to",parseInt(a,10)+","+parseInt(c.Base.trendsPlace.y+c.Base.trendsPlace.h,10));h.setAttribute("stroke","true");h.setAttribute("strokecolor","#"+e.divlinecolor);h.setAttribute("strokeweight","1");h.style.position="absolute";h.style.top="0px";h.style.left="0px";h.style.width=c.width+"px";h.style.height=c.height+"px";c.NodeStore.root.appendChild(h);h=c.NodeFactory.VML.createNode("textbox");h.appendChild(document.createTextNode(b));var h=c.NodeFactory.VML.addStylesToCategoriesLabel(h),
l=c.NodeFactory.VML.getBiggestBBox([b],{fontFamily:h.fontFamily,fontSize:h.fontSize});"0"===e.rotateNames?c.NodeFactory.VML.addLabel(b,f,g+parseInt(l.h/2,10),!1,{font:h.fontFamily,size:h.fontSize,color:h.fontColor}):c.NodeFactory.VML.addLabel(b,f,g+2+parseInt(l.w/2,10),!0,{font:h.fontFamily,size:h.fontSize,color:h.fontColor})},drawHorizontalDivLine:function(a,b,c,e){var f=Trend[k],g=f.NodeFactory.VML.createNode("shape");g.setAttribute("strokecolor","#"+b);g.setAttribute("strokeweight",c);g.setAttribute("coordorigin",
"0 0");g.setAttribute("coordsize",f.width+" "+f.height);g.setAttribute("path","m "+parseInt(f.Base.trendsPlace.x,10)+","+parseInt(a,10)+" l "+parseInt(f.Base.trendsPlace.x+f.Base.trendsPlace.w,10)+","+parseInt(a,10));g.style.position="absolute";g.style.top="0px";g.style.left="0px";g.style.width=f.width+"px";g.style.height=f.height+"px";e&&(a=f.NodeFactory.VML.createNode("stroke"),a.setAttribute("dashstyle","dash"),g.appendChild(a));f.NodeStore.root.appendChild(g)},drawHorizontalLineLabel:function(a,
b,c){var e=Trend[k],f=e.params.xmlData.chart,g=e.Base.trendsPlace.x-1,h=e.NodeFactory.VML.createNode("textbox");h.style.position="absolute";h.style.left=g+"px";h.style.top=a+"px";h.style.fontFamily=f.outCnvBaseFontColor;h.style.fontSize=f.outCnvBaseFontSize+"px";h.style.color="#"+c;h.appendChild(document.createTextNode(b));e.chartContainer.appendChild(h);b=e.getSize(h);e.NodeStore.root.appendChild(h);h.style.left=g-b.width+"px";h.style.top=a-b.height/2+"px"},drawHorizontalSection:function(a,b,c,e){var f=
Trend[k],g=f.NodeFactory.VML.createNode("rect",!0);g.style.top=parseInt(b,10)+"px";g.style.left=parseInt(f.Base.trendsPlace.x,10)+"px";g.style.width=parseInt(f.Base.trendsPlace.w,10)+"px";g.style.height=parseInt(a-b,10)+"px";g.style.position="absolute";a=f.NodeFactory.VML.createNode("fill");a.setAttribute("color","#"+c);a.setAttribute("opacity",parseInt(e,10)+"%");g.appendChild(a);f.NodeStore.root.appendChild(g)},drawLine:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=b.NodeFactory.VML.createNode("line",
!0),f=null;e.setAttribute("from",parseInt(a.fromX,10)+","+parseInt(a.fromY,10));e.setAttribute("to",parseInt(a.toX,10)+","+parseInt(a.toY,10));e.childNodes[0].setAttribute("opacity",parseInt(c.lineAlpha,10)+"%");e.style.position="absolute";e.style.top="0px";e.style.left="0px";e.style.width=b.width+"px";e.style.height=b.height+"px";(f=null!==a.lineThickness?a.lineThickness:c.lineThickness)&&e.setAttribute("strokeweight",parseInt(f,10));if(null!==a.showShadow){var g=b.Base.shadowOffset,h=b.NodeFactory.VML.createNode("line",
!0);h.setAttribute("from",parseInt(a.fromX+g,10)+","+parseInt(a.fromY+g,10));h.setAttribute("to",parseInt(a.toX+g,10)+","+parseInt(a.toY+g,10));h.setAttribute("stroke","true");h.setAttribute("strokecolor","#999999");h.childNodes[0].setAttribute("opacity",parseInt(b.Base.shadowOpacity,10)+"%");h.style.position="absolute";h.style.top="0px";h.style.left="0px";h.style.width=b.width+"px";h.style.height=b.height+"px";f&&h.setAttribute("strokeweight",parseInt(parseInt(f,10)*b.Base.shadowWidthCoef,10));b.NodeStore.root.appendChild(h)}g=
b.NodeFactory.VML.createNode("stroke");g.setAttribute("color","#"+a.color.replace("#",""));e.appendChild(g);b.NodeStore.root.appendChild(e);c={line:e,width:f,color:a.color,alpha:parseInt(c.lineAlpha,10)};a=new b.NodeFactory.VML.anchorHoverHandler(void 0,c);c=new b.NodeFactory.VML.anchorOutHandler(c);b.addEvent(e,"mouseover",a);b.addEvent(e,"mouseout",c)},anchorHoverHandler:function(a,b,c,e){return function(){var f=Trend[k],g=f.params.xmlData.chart;if("undefined"!==typeof b)if("default"===g.lineHoverColor){var g=
f.Base.changeColor(b.color.replace("#",""),25).hexCode,h=f.NodeFactory.VML.createNode("stroke");h.setAttribute("opacity","1");h.setAttribute("color","#"+g.replace("#",""));h.setAttribute("weight",b.width);var l=b.line.lastChild;b.line.removeChild(l);b.line.appendChild(h)}else"none"!==g.lineHoverColor&&(l=b.line.lastChild,b.line.removeChild(l),h=f.NodeFactory.VML.createNode("stroke"),h.setAttribute("opacity","1"),h.setAttribute("color","#"+g.lineHoverColor.replace("#","")),h.setAttribute("weight",
b.width),b.line.appendChild(h));"undefined"!==typeof a&&""!==a&&f.ToolTip.show(a);"undefined"!==typeof c&&(e.radius+=3,c.style.position="absolute",c.style.left=parseInt(e.x-e.radius,10)+"px",c.style.top=parseInt(e.y-e.radius,10)+"px",c.style.width=2*e.radius+"px",c.style.height=2*e.radius+"px")}},anchorOutHandler:function(a,b,c){return function(){var e=Trend[k];if("undefined"!==typeof a){a.line.removeChild(a.line.lastChild);var f=e.NodeFactory.VML.createNode("stroke");f.setAttribute("opacity","1");
f.setAttribute("color","#"+a.color.replace("#",""));f.setAttribute("weight",a.width);a.line.appendChild(f)}e.ToolTip.hide();"undefined"!==typeof b&&(c.radius-=3,b.style.position="absolute",b.style.left=parseInt(c.x-c.radius,10)+"px",b.style.top=parseInt(c.y-c.radius,10)+"px",b.style.width=2*c.radius+"px",b.style.height=2*c.radius+"px")}},drawAnchor:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=b.NodeFactory.VML.createNode("oval"),f=parseInt(c.anchorRadius,10),g={radius:f,x:a.x,y:a.y};e.style.position=
"absolute";e.style.left=a.x-f+"px";e.style.top=a.y-f+"px";e.style.width=2*f+"px";e.style.height=2*f+"px";f=b.NodeFactory.VML.createNode("fill");f.setAttribute("color","#"+c.anchorBgColor);f.setAttribute("opacity",parseInt(c.anchorAlpha,10)+"%");e.appendChild(f);f=b.NodeFactory.VML.createNode("stroke");f.setAttribute("color","#"+a.color.replace("#",""));f.setAttribute("weight",c.anchorBorderThickness);f.setAttribute("opacity",parseInt(c.anchorAlpha,10)+"%");e.appendChild(f);if("1"===a.showValues){var f=
b.NodeFactory.VML.createNode("textbox"),h=b.Base.anchorLabelOffset,l=a.x,j=a.y-h,m=c.numberPrefix+parseFloat(a.value,10).toFixed(c.decimals)+c.numberSuffix;j<b.Base.trendsPlace.y&&(j=a.y+h);f.appendChild(document.createTextNode(m));f.style.fontFamily=c.baseFont;f.style.fontSize=c.baseFontSize+"px";f.style.color=c.baseFontColor;f.style.position="absolute";b.NodeStore.root.appendChild(f);c=b.getSize(f);f.style.left=l-c.width/2+"px";f.style.top=j-c.height/2+"px"}c=new b.NodeFactory.VML.anchorHoverHandler(a.toolText,
void 0,e,g);g=new b.NodeFactory.VML.anchorOutHandler(void 0,e,g);b.NodeStore.root.appendChild(e);b.addEvent(e,"mouseover",c);b.addEvent(e,"mouseout",g);""!==a.url&&(e.style.cursor="pointer",b.addEvent(e,"click",function(){window.open(a.url,"_blank")}))},getBiggestBBox:function(a,b){var c=Trend[k],e=a.length,f=document.createElement("div"),g=0,h=0;f.style.top="-100px";f.style.left="-100px";f.style.position="absolute";f.style.fontFamily=b.fontFamily;f.style.fontSize=b.fontSize+"px";for(c.chartContainer.appendChild(f);e--;){c.deleteChilds(f);
f.appendChild(document.createTextNode(a[e]));var l=c.getSize(f);g<l.width&&(g=l.width);h<l.height&&(h=l.height)}c.chartContainer.removeChild(f);return{w:g,h:h}},addStylesToTextObject:function(a,b){a.style.fontFamily=b.font;a.style.fontSize=b.size+"px";"1"==b.bold&&(a.style.fontWeight="bold");a.style.color="#"+b.color},drawLegendBackground:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=b.NodeFactory.VML.createNode("rect",!0);e.style.top=a.y+"px";e.style.left=a.x+"px";e.style.width=a.w+"px";
e.style.height=a.h+"px";e.style.position="absolute";e.setAttribute("fillcolor","#"+c.legendBgColor);b.NodeStore.root.appendChild(e)},addStylesToCategoriesLabel:function(a){var b=Trend[k].params.xmlData.chart,c=b.outCnvBaseFont,e=b.outCnvBaseFontSize,f=b.outCnvBaseFontColor;"undefined"!==typeof b.categories.font&&(c=b.categories.font);"undefined"!==typeof b.categories.fontSize&&(e=b.categories.fontSize);"undefined"!==typeof b.categories.fontColor&&(f=b.categories.fontColor);"undefined"!==typeof a&&
(a.style.fontFamily=c,a.style.fontSize=e+"px",a.style.color="#"+f);return{fontFamily:c,fontSize:e,fontColor:f}}},Canvas:{createRoot:function(){var a=Trend[k],b=document.createElement("canvas");b.setAttribute("id","can");b.style.position="relative";b.style.top="0 px";b.style.left="0 px";a.chartContainer.appendChild(b);b.setAttribute("width",a.width);b.setAttribute("height",a.height);a.NodeStore.root=b.getContext("2d")},drawLogo:{innerOverlayGradient:null,outerOverlayGradient:null,init:function(){var a=
Trend[k],b=a.NodeStore.root,c=a.width-130,e=a.height-50,f=""+parseInt(1073741824*Math.random(),10);a.NodeFactory.Canvas.drawLogo.createGradient(b,f,{cx:c+20,cy:e+20,radius:30});a.NodeFactory.Canvas.drawLogo.drawCirclePart({angleStart:70,angleEnd:340,color:a.NodeFactory.Canvas.drawLogo.outerOverlayGradient,cx:c+20,cy:e+20,radius:20,container:b});a.NodeFactory.Canvas.drawLogo.drawCirclePart({angleStart:-20,angleEnd:70,color:"#F26734",cx:c+20+2,cy:e+20+1,radius:20,container:b});a.NodeFactory.Canvas.drawLogo.createText(b,
c+20+9,e+20+13)},drawPoly:function(a){var b=Trend[k].NodeStore.root,c=a.points,e=c.length-1;b.globalAlpha=1;b.save();b.beginPath();for(b.moveTo(c[e].x,c[e].y);e--;)b.lineTo(c[e].x,c[e].y);b.fillStyle=a.color;b.lineWidth=1;b.closePath();b.fill();b.globalAlpha=1;b.restore()},drawCirclePart:function(a){var b=Trend[k],c=[],e=a.cx,f=a.cy,g=a.radius;c.push({x:e,y:f});for(var h=a.angleStart;h<=a.angleEnd;h++){var l=h*(Math.PI/180),j=0,m=0,j=e+g*Math.cos(l),m=f+g*Math.sin(l);c.push({x:j,y:m})}b.NodeFactory.Canvas.drawLogo.drawPoly({points:c,
color:a.color,container:a.container})},createGradient:function(a,b,c){a=Trend[k];var e=a.NodeStore.root;b=e.createLinearGradient(0,0,0,a.height);c=e.createRadialGradient(c.cx,c.cy,0,c.cx,c.cy,30);b.addColorStop(0,"rgba(255,255,255,0.0)");b.addColorStop(1,"rgba(255,255,255,0.4)");c.addColorStop(0,"rgba(0,0,0,0.5)");c.addColorStop(1,"rgba(0,0,0,0.5)");a.NodeFactory.Canvas.drawLogo.innerOverlayGradient=b;a.NodeFactory.Canvas.drawLogo.outerOverlayGradient=c},createText:function(a,b,c){a=Trend[k].NodeStore.root;
var e="Tahoma",f="15",g="434343";a.save();a.font=f+"px  "+e+" bold";a.fillStyle="#"+g;a.textAlign="center";a.translate(b+10,c);a.fillText("HD",0,0);a.restore();e="Tahoma";f="15";g="F15A23";a.save();a.font=f+"px  "+e+" bold";a.fillStyle="#"+g;a.textAlign="center";a.translate(b+52,c);a.fillText("CHARTS",0,0);a.restore()}},initBackgroundGradient:function(a,b,c){var e=Trend[k],f=e.NodeStore.root;c=parseInt(c,10);switch(c+90){case 0:var g=f.createLinearGradient(0,e.height,e.width,e.height);break;case 45:g=
f.createLinearGradient(0,e.height,e.width,0);break;case 90:g=f.createLinearGradient(0,e.height,0,0);break;case 135:g=f.createLinearGradient(e.width,e.height,0,0);break;case 180:g=f.createLinearGradient(e.width,e.height/2,0,e.height/2);break;case 225:g=f.createLinearGradient(e.width,0,0,e.height);break;case 270:g=f.createLinearGradient(e.width/2,0,e.width/2,e.height);break;case 315:g=f.createLinearGradient(0,0,e.width,e.height);break;case 360:g=f.createLinearGradient(0,e.height,e.width,e.height);break;
case 405:g=f.createLinearGradient(0,e.height,e.width,0);break;case 495:g=f.createLinearGradient(0,0,0,e.height)}g.addColorStop(0,a);g.addColorStop(1,b);return g},createBackground:function(){var a=Trend[k],b=a.NodeStore.root,c=a.params.xmlData.chart,e=c.bgColor.split(",");b.beginPath();b.rect(0,0,a.width,a.height);1!==e.length?b.fillStyle="#"+e[0]:(a=a.NodeFactory.Canvas.initBackgroundGradient("#"+e[0],"#"+e[1],c.bgAngle),b.fillStyle=a);b.globalAlpha=c.bgAlpha/100;b.fill();b.lineWidth=0;b.globalAlpha=
1},drawChartCanvas:function(){var a=Trend[k],b=a.params.xmlData.chart,c=a.NodeStore.root;c.beginPath();c.rect(parseInt(a.Base.trendsPlace.x,10),parseInt(a.Base.trendsPlace.y,10),parseInt(a.Base.trendsPlace.w,10),parseInt(a.Base.trendsPlace.h,10));var e=b.canvasBgColor.split(",");1==e.length?c.fillStyle="#"+e[0]:(a=a.NodeFactory.Canvas.initBackgroundGradient("#"+e[0],"#"+e[1],b.bgAngle),c.fillStyle=a);c.globalAlpha=b.canvasBgAlpha/100;c.fill();c.lineWidth=b.canvasBorderThickness;c.strokeStyle="#"+
b.canvasBorderColor;c.stroke()},getSize:function(a,b){var c=Trend[k],e=document.createElement("div");e.style.position="absolute";e.style.top="0px";e.style.left="0px";e.style.fontFamily=b.font;e.style.fontSize=b.fontSize+"px";e.appendChild(document.createTextNode(a));c.params.container.appendChild(e);var f=c.getSize(e);c.params.container.removeChild(e);return f},drawVerticalDivLine:function(a,b){var c=Trend[k],e=c.params.xmlData.chart,f=a-c.Base.leftLabelsOffset,g=c.Base.trendsPlace.y+c.Base.trendsPlace.h,
h=c.NodeStore.root;h.beginPath();h.lineWidth=1;h.strokeStyle="#"+e.divlinecolor;h.moveTo(a,c.Base.trendsPlace.y);h.lineTo(a,c.Base.trendsPlace.y+c.Base.trendsPlace.h);h.stroke();var l=c.NodeFactory.Canvas.addStylesToCategoriesLabel(),j=c.NodeFactory.Canvas.getSize(b,{font:l.fontFamily,fontSize:l.fontSize});c.NodeFactory.Canvas.addStylesToTextObject({font:l.fontFamily,size:l.fontSize,color:l.fontColor});"0"===e.rotateNames?h.fillText(b,f-j.width/2,g+j.height):(h.save(),h.translate(f,g),h.rotate(-Math.PI/
2),h.textAlign="center",h.fillText(b,-j.width/2-1,j.height/2),h.restore())},drawHorizontalDivLine:function(a,b,c){var e=Trend[k],f=e.NodeStore.root;f.beginPath();f.lineWidth=c;f.strokeStyle="#"+b;f.moveTo(e.Base.trendsPlace.x,a);f.lineTo(e.Base.trendsPlace.x+e.Base.trendsPlace.w,a);f.stroke()},drawHorizontalLineLabel:function(a,b,c){var e=Trend[k],f=e.params.xmlData.chart,g=e.Base.trendsPlace.x,h=e.NodeStore.root,l=e.NodeFactory.Canvas.getSize(b,{font:f.outCnvBaseFont,fontSize:f.outCnvBaseFontSize});
e.NodeFactory.Canvas.addStylesToTextObject({font:f.outCnvBaseFont,size:f.outCnvBaseFontSize,color:c});h.fillStyle="#"+c;h.fillText(b,g-l.width-2,a+l.height/4)},drawHorizontalSection:function(a,b,c,e){var f=Trend[k],g=f.NodeStore.root;g.beginPath();g.rect(f.Base.trendsPlace.x,a,f.Base.trendsPlace.w,b-a);g.fillStyle="#"+c;g.globalAlpha=e/100;g.fill();g.lineWidth=0;g.globalAlpha=1},drawLine:function(a){var b=Trend[k],c=b.params.xmlData.chart,e=b.NodeStore.root,f=2,f=null!==a.lineThickness?a.lineThickness:
c.lineThickness;if(null!==a.showShadow){var g=b.Base.shadowOffset;e.beginPath();e.lineWidth=f;e.fillStyle="#999999";e.strokeStyle="#999999";e.globalAlpha=b.Base.shadowOpacity/100;e.moveTo(a.fromX+g,a.fromY+g);e.lineTo(a.toX+g,a.toY+g);e.stroke()}e.beginPath();e.lineWidth=parseInt(parseInt(f,10)*b.Base.shadowWidthCoef,10);e.fillStyle="#"+a.color;e.strokeStyle="#"+a.color;e.globalAlpha=c.lineAlpha/100;e.moveTo(a.fromX,a.fromY);e.lineTo(a.toX,a.toY);e.stroke();e.globalAlpha=1},drawAnchor:function(a){var b=
Trend[k],c=b.params.xmlData.chart,e=b.NodeStore.root,f=parseInt(c.anchorRadius,10);e.beginPath();e.arc(a.x,a.y,f,0,2*Math.PI,!0);e.fillStyle="#"+c.anchorBgColor;e.globalAlpha=c.anchorAlpha/100;e.fill();e.lineWidth=c.anchorBorderThickness;e.strokeStyle="#"+a.color;e.stroke();e.globalAlpha=1;if("1"===a.showValues){var f=b.Base.anchorLabelOffset,g=a.x,h=a.y-f,l=c.numberPrefix+parseFloat(a.value,10).toFixed(c.decimals)+c.numberSuffix,j=b.NodeFactory.Canvas.getSize(l,{font:c.baseFont,fontSize:c.baseFontSize});
b.NodeFactory.Canvas.addStylesToTextObject({font:c.baseFont,size:c.baseFontSize,color:c.baseFontColor});h<b.Base.trendsPlace.y&&(h=a.y+f);e.fillStyle="#"+c.baseFontColor;e.fillText(l,g-j.width/2,h+j.height/4)}},getBiggestBBox:function(a,b){var c=Trend[k],e=a.length,f=document.createElement("div"),g=0,h=0;f.style.top="-100px";f.style.left="-100px";f.style.position="absolute";f.style.fontFamily=b.fontFamily;f.style.fontSize=b.fontSize+"px";for(c.chartContainer.appendChild(f);e--;){c.deleteChilds(f);
f.appendChild(document.createTextNode(a[e]));var l=c.getSize(f);g<l.width&&(g=l.width);h<l.height&&(h=l.height)}c.chartContainer.removeChild(f);return{w:g,h:h}},addStylesToTextObject:function(a){var b=Trend[k].NodeStore.root,c="",c="undefined"!==typeof a.italic?"1"==a.italic?c+"italic ":c+"normal ":c+"normal ",c="undefined"!==typeof a.bold?"1"==a.bold?c+"bold ":c+"normal ":c+"normal ",c="undefined"===typeof a.size?c+"11px ":c+a.size+"px ",c="undefined"===typeof a.font?c+"Tahoma ":c+a.font;b.font=
c;b.fillStyle="undefined"!==typeof a.color?"#"+a.color:"#000000"},drawLegendBackground:function(){var a=Trend[k],b=a.Base.legendSize,a=a.NodeStore.root;a.beginPath();a.fillStyle="#EAEAEA";a.fillRect(b.x,b.y,b.w,b.h);a.fill();a.shadowColor="rgba(0, 0, 0, 0)";a.shadowOffsetX=0;a.shadowOffsetY=0;a.shadowBlur=0},addStylesToCategoriesLabel:function(){var a=Trend[k].params.xmlData.chart,b=a.outCnvBaseFont,c=a.outCnvBaseFontSize,e=a.outCnvBaseFontColor;"undefined"!==typeof a.categories.font&&(b=a.categories.font);
"undefined"!==typeof a.categories.fontSize&&(c=a.categories.fontSize);"undefined"!==typeof a.categories.fontColor&&(e=a.categories.fontColor);return{fontFamily:b,fontSize:c,fontColor:e}}}}};return{width:0,height:0,chart:window.Trend[k],data:n,initialize:function(a,b){window.Trend[k].initialize(a,b);this.width=a;this.height=b},redraw:function(a){"undefined"===typeof a?a=this.data:this.data=a;window.Trend[k].initialize(this.width,this.height,a)}}}throw Error("TrendChart Error: Incorect data passed to TrendChart ( container, jsData, chartId )!");
}
function TrendChartXML(s,n,k){if("undefined"!==typeof s&&null!=s&&"undefined"!==typeof n){var v=function(a){var c=null;if(window.DOMParser)try{c=(new DOMParser).parseFromString(a,"text/xml")}catch(e){c=null}else if(window.ActiveXObject)try{if(c=new ActiveXObject("Microsoft.XMLDOM"),c.async=!1,!c.loadXML(a))throw Error(c.parseError.reason+c.parseError.srcText);}catch(f){c=null}else throw Error("cannot parse xml string!");return c},a=function(a){var c={toObj:function(a){var b={};if(1==a.nodeType){if(a.attributes.length)for(var g=0;g<
a.attributes.length;g++)b[a.attributes[g].nodeName]=(a.attributes[g].nodeValue||"").toString();if(a.firstChild){for(var h=g=0,l=!1,j=a.firstChild;j;j=j.nextSibling)1==j.nodeType?l=!0:3==j.nodeType&&j.nodeValue.match(/[^ \f\n\r\t\v]/)?g++:4==j.nodeType&&h++;if(l)if(2>g&&2>h){c.removeWhite(a);for(j=a.firstChild;j;j=j.nextSibling)3==j.nodeType?b["#text"]=c.escape(j.nodeValue):4==j.nodeType?b["#cdata"]=c.escape(j.nodeValue):b[j.nodeName]?b[j.nodeName]instanceof Array?b[j.nodeName][b[j.nodeName].length]=
c.toObj(j):b[j.nodeName]=[b[j.nodeName],c.toObj(j)]:b[j.nodeName]=c.toObj(j)}else a.attributes.length?b["#text"]=c.escape(c.innerXml(a)):b=c.escape(c.innerXml(a));else if(g)a.attributes.length?b["#text"]=c.escape(c.innerXml(a)):b=c.escape(c.innerXml(a));else if(h)if(1<h)b=c.escape(c.innerXml(a));else for(j=a.firstChild;j;j=j.nextSibling)b["#cdata"]=c.escape(j.nodeValue)}!a.attributes.length&&!a.firstChild&&(b=null)}else 9==a.nodeType?b=c.toObj(a.documentElement):alert("unhandled node type: "+a.nodeType);
return b},toJson:function(a,b,g){var h=b?'"'+b+'"':"";if(a instanceof Array){for(var l=0,j=a.length;l<j;l++)a[l]=c.toJson(a[l],"",g+"\t");h+=(b?":[":"[")+(1<a.length?"\n"+g+"\t"+a.join(",\n"+g+"\t")+"\n"+g:a.join(""))+"]"}else if(null==a)h+=(b&&":")+"null";else if("object"==typeof a){l=[];for(j in a)l[l.length]=c.toJson(a[j],j,g+"\t");h+=(b?":{":"{")+(1<l.length?"\n"+g+"\t"+l.join(",\n"+g+"\t")+"\n"+g:l.join(""))+"}"}else h="string"==typeof a?h+((b&&":")+'"'+a.toString()+'"'):h+((b&&":")+a.toString());
return h},innerXml:function(a){var b="";if("innerHTML"in a)b=a.innerHTML;else{var c=function(a){var b="";if(1==a.nodeType){for(var b=b+("<"+a.nodeName),e=0;e<a.attributes.length;e++)b+=" "+a.attributes[e].nodeName+'="'+(a.attributes[e].nodeValue||"").toString()+'"';if(a.firstChild){b+=">";for(e=a.firstChild;e;e=e.nextSibling)b+=c(e);b+="</"+a.nodeName+">"}else b+="/>"}else 3==a.nodeType?b+=a.nodeValue:4==a.nodeType&&(b+="<![CDATA["+a.nodeValue+"]]\x3e");return b};for(a=a.firstChild;a;a=a.nextSibling)b+=
c(a)}return b},escape:function(a){return a.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(a){a.normalize();for(var b=a.firstChild;b;)if(3==b.nodeType)if(b.nodeValue.match(/[^ \f\n\r\t\v]/))b=b.nextSibling;else{var g=b.nextSibling;a.removeChild(b);b=g}else 1==b.nodeType&&c.removeWhite(b),b=b.nextSibling;return a}};9==a.nodeType&&(a=a.documentElement);return"{\n"+c.toJson(c.toObj(c.removeWhite(a)),a.nodeName,"\t").replace(/\t|\n/g,
"")+"\n}"};return{parseXml:v,XMLtoJSON:a,xmlStr:n,chart:null,container:s,symbols:[{symbol:/!#amp!/g,replacement:"&"},{symbol:/%26lt;/g,replacement:"<"},{symbol:/%26gt;/g,replacement:">"}],encodeString:function(a){for(var c=this.symbols,e=c.length;e--;)a=a.replace(c[e].symbol,c[e].replacement);return a},getParamsFromXML:function(b){b=b.replace(/&/g,"!#amp!");b=v(b);b=a(b);b=this.encodeString(b);b=eval("("+b+")");var c={};if("undefined"!==typeof b.parsererror)throw Error("XML parse error in TrendChart lib");
c.xmlData=b;c.container=this.container;return c},initialize:function(a,c){var e=this.getParamsFromXML(this.xmlStr),e=new TrendChart(s,e,k);e.initialize(a,c);this.chart=e},redrawXML:function(a){a=this.getParamsFromXML(a);this.chart.redraw(a)}}}throw Error("TrendChart Error: Incorrect parameters passed to TrendChartXML ( container, xmlStr )!");};